### ISSUE TITLE
Can't get project set up with or without using Expo

### ISSUE THREAD

**Issue by LucasVanDongen** [GetStream/react-native-activity-feed#10]
**Describe the bug**
I have an existing project I want to add this library to. I'm new to React Native but experienced in iOS.
**To Reproduce**
1. Created the project with `create-react-native-app AppName`
2. Ran `npm i react-native-activity-feed --save`
3. The default application in the `ios` folder doesn't build and run
4. Replaced it with the native iOS application I wanted to add your component to and added the following CocoaPods:

```
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

```
5. I've added the following code to load the view:
```
    private let customView: RCTRootView = {
        let jsCodeLocation = URL(string: "http://192.168.27.170:8081/App.bundle?platform=ios")
        let mockData: NSDictionary = ["scores":
            [
                ["name":"Alex", "value":"42"],
                ["name":"Joel", "value":"10"]
            ]
        ]
        return RCTRootView(
            bundleURL: jsCodeLocation,
            moduleName: "App",
            initialProperties: mockData as [NSObject : AnyObject],
            launchOptions: nil
        )
    }()
```
6. I've started the server with `react-native start`
7. When loading `http://192.168.27.170:8081/App.bundle?platform=ios` I started getting messages about missing modules:
8. Added `npm i expo-activity-feed --save`, `expo` and `react-native-safe-area-view`
9. bundle URL works fine now
10. When booting the application and navigating to the screen I get: `The Expo SDK requires Expo to run`. 

**Expected behavior**
It should have worked just following the steps in the README. Now I'm dealing with package problems and Expo without ever wanting Expo.

**Setup:**
 - iOS
-  React Native but somehow I can't escape Expo?
 - React Native Version: 0.57.5
 - `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
 - `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`

**Additional context**
```
import React from 'react';
import SafeAreaView from 'react-native-safe-area-view';
import { 
    StreamApp,
    FlatFeed,
    Activity,
    LikeButton, 
} from 'react-native-activity-feed';

const CustomActivity = (props) => {
  return (
    <Activity
      {...props}
      Footer={
        <LikeButton {...props} />
      }
    />
  );
};

const App = () => {
  return (
    <SafeAreaView style={{flex: 1}} forceInset={{ top: 'always' }}>
      <StreamApp
          apiKey="bla"
          appId="bla"
          token="bla">
        <FlatFeed Activity={CustomActivity} />
      </StreamApp>
    </SafeAreaView>
  );
};

export default App;
```

**Comment by LucasVanDongen** [comment]
Update: the App.js file was the wrong one, I got stuck at:

`Module AppRegistry is not a registered callable module (calling runApplication)`

**Comment by JelteF** [comment]
I will close this since running react native inside a normal iOS app is outside of the scope of this project. We're working on native Swift components at the moment as well.
