### ISSUE TITLE
Stream Api error 

### ISSUE THREAD

**Issue by savithri-lab** [GetStream/react-native-activity-feed#107]
StreamApiError {error: {…}, response: XMLHttpRequest, message: "{"detail":"Errors for fields 'activity_id', 'paren…]},"duration":"0.14ms"} with HTTP status code 400", stack: "Error: {"detail":"Errors for fields 'activity_id',…e?platform=android&dev=true&minify=false:3318:37)"}error: {detail: "Errors for fields 'activity_id', 'parent'", status_code: 400, code: 4, exception: "InputException", exception_fields: {…}, …}response: XMLHttpRequest {UNSENT: 0, OPENED: 1, HEADERS_RECEIVED: 2, LOADING: 3, DONE: 4, …}message: "{"detail":"Errors for fields 'activity_id', 'parent'","status_code":400,"code":4,"exception":"InputException","exception_fields":{"activity_id":["one of activity_id or parent must not be empty"],"parent":["one of activity_id or parent must not be empty"]},"duration":"0.14ms"} with HTTP status code 400"stack: "Error: {"detail":"Errors for fields 'activity_id', 'parent'","status_code":400,"code":4,"exception":"InputException","exception_fields":{"activity_id":["one of activity_id or parent must not be empty"],"parent":["one of activity_id or parent must not be empty"]},"duration":"0.14ms"} with HTTP status code 400↵

**Comment by tbarbugli** [comment]
Please include some more context like the code

**Comment by vishalnarkhede** [comment]
Hey @savithri-lab , we are closing this issue due to lack of information. If you are still facing the issue, please give us more details and reopen the issue :)
