### ISSUE TITLE
Are Typescript typings available?

### ISSUE THREAD

**Issue by OzzieOrca** [GetStream/react-native-activity-feed#108]
I'm only seeing flow types. I'm most interested in types for `react-native-activity-feed`.

Has any effort been put into this? Any way to help? I'm evaluating this platform and a lack of types will be annoying.

**Comment by tschellenbach** [comment]
Yeah we made a mistake using Flow for this.

Our chat API JS sdks are moving to typescript, feeds will follow in the future (I suspect at least 3 months out at this point). If you want to fork and do a PR we'll definitely merge it.

**Comment by snmishra** [comment]
I had converted the Flow types to Typescript types for my own project. Not the best, but it worked alright for me. If there's interest, I can see if I can extract and upload them.

**Comment by jaapbakker88** [comment]
There's definitely interest,  but right now we're very busy converting our other libraries.

**Comment by district-michael** [comment]
@tschellenbach any movement on migrating these libraries to TS?  I noticed that the chat libraries just moved across, so hoping these libraries will also be moving soon 🤞

**Comment by tschellenbach** [comment]
We had a good experience with TS on the chat libs, these will definitely follow, but it's not on the immediate roadmap
