### ISSUE TITLE
Signature is invalid

### ISSUE THREAD

**Issue by AdamGold** [GetStream/react-native-activity-feed#117]
**Setup (always fill this in):**

- iOS
- regular React Native
- React Native Version: 0.61.1
- `react-native-activity-feed`: 0.8.21

**Describe the bug**
The following is how I implement `GetStream`:
```javascript
<StreamApp
	apiKey={STREAM_API_KEY}
	appId={STREAM_API_SECRET}
	userId={this.props.user.id.toString()}
	token={this.state.streamToken}
>
	<FlatFeed userId={this.props.user.id.toString()} />
	<StatusUpdateForm />
</StreamApp>
```

I get an alert saying "Signature is invalid", although that user exists in the app and the key, secret & token are correct. The token is being generated in the backend for each user.

**Comment by akhatriST** [comment]
@AdamGold How did you resolve this issue? I am getting this error as well

**Comment by AdamGold** [comment]
@akhatriST I was using the wrong tokens.

**Comment by akhatriST** [comment]
@AdamGold I see, thanks for the response.
