### ISSUE TITLE
Realtime Reactions

### ISSUE THREAD

**Issue by AdamGold** [GetStream/react-native-activity-feed#118]
**Setup (always fill this in):**

- iOS
- regular React Native
- React Native Version: 0.61.1
- `react-native-activity-feed`version: 0.8.21

**Describe the bug**
When adding a new reaction/comment via `CommentBox` or `ReactionIcon`, nothing gets updated in realtime. A refresh must be done.
I couldn't find any place describing how to get the reactions to update in real time.

**To Reproduce**
```javascript
<StreamApp
	apiKey={STREAM_API_KEY}
	appId={STREAM_APP_ID}
	userId={this.props.user.id.toString()}
	token={t}
>
	<FlatFeed
		feedGroup="user"
		userId={this.props.user.id.toString()}
		options={{
			withRecentReactions: true,
			withOwnReactions: true
		}}
		Activity={props => {
			const {
				time,
				actor,
				reaction_counts
			} = props.activity
			return (
				<Activity
					{...props}
					Footer={() => (
						<View>
							<ReactionIconBar>
								<ReactionToggleIcon
									inactiveIcon={HeartIcon}
									activeIcon={HeartIcon}
									kind={"like"}
									counts={reaction_counts}
									width={24}
									height={24}
									onPress={() => {
										this.addReaction(
											"like",
											props.activity
										)
									}}
								/>
							</ReactionIconBar>
							<CommentList
								activityId={props.activity.id}
							/>
							<CommentBox
								onAddReaction={(
									kind,
									activity,
									data
								) => {
									this.addReaction(
										kind,
										props.activity,
										data
									)
								}}
							/>
						</View>
					)}
				/>
			)
		}}
	/>
</StreamApp>
```

`addReaction` calls the API which in turn calls the `stream` client.

**Comment by nishiloxit** [comment]
Hey @AdamGold , did you manage to resolve this? I am facing a similar issue. When I add a comment, it doesnt auto-add itself into the ReactionList I am using to render comments.

**Comment by wmarsey** [comment]
Hi @AdamGold @nishiloxit did either of you find a fix for this? I've been hacking at this all day with no solution...
