### ISSUE TITLE
NewActivitiesNotification : can't change language

### ISSUE THREAD

**Issue by AlexisJamin** [GetStream/react-native-activity-feed#12]
Hello,

It is impossible to change "You have X new ...". Only the last word can be customized. 

Can you create a prop that enables us to change the beginning of the sentence please ? My users are French speakers. Soon Italian, Spanish and German ! 

Big Thanks !

**Comment by JelteF** [comment]
The easiest is probably to create your own NewActivitiesNotification component (here's the [source](https://github.com/GetStream/react-native-activity-feed/blob/master/src/components/NewActivitiesNotification.js)). And then you can pass that component to the FlatFeed or NotificationFeed [`Notifier` prop](https://getstream.github.io/react-native-activity-feed/#flatfeed).

**Comment by AlexisJamin** [comment]
@JelteF thanks for your quick answer. I'm thinking of it. 

But I believe that if GetStream wants to become global, they should add an option for other languages ! :-)

**Comment by AlexisJamin** [comment]
I've just created a pull request. Can you merge @JelteF ? :-)

**Comment by JelteF** [comment]
Just released v0.6.10 which adds the labelFunction prop to NewActivitiesNotification
