### ISSUE TITLE
i18n json files missing from package

### ISSUE THREAD

**Issue by snmishra** [GetStream/react-native-activity-feed#123]
**Setup (always fill this in):**

- Android
- regular React Native
- React Native Version: 0.62
- `react-native-activity-feed` : 0.9.0
- `getstream` version: 4.5.1

**Describe the bug**
The json files from recently merged i18n feature are missing in published package

**To Reproduce**

1. Upgrade react-native-activity-feed to 0.9.0
2. Build and run react-native app
3. metro bundler gives error

**Expected behavior**
Build should complete

**Additional context**
```
error: Error: Unable to resolve module `../i18n/en.json` from `node_modules\react-native-activity-feed-core\lib\i18n\index.js`:

None of these files exist:
  * en.json
  * node_modules\react-native-activity-feed-core\lib\i18n\en.json\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

**Comment by vishalnarkhede** [comment]
Hey @snmishra thanks for this. Looking into it ...

**Comment by vishalnarkhede** [comment]
Hey @snmishra , please use `0.9.1`. I have fixed the package :)

Let me know if it works!

**Comment by snmishra** [comment]
Thanks, that was an impressive turn around time. Works now.
