### ISSUE TITLE
FlatFeed filtered by reactions

### ISSUE THREAD

**Issue by luisfuertes** [GetStream/react-native-activity-feed#140]
Im trying to show FlatFeed filtered by reaction, example "like" to show only my "like" reactions activities.

How can i get this data with pagination?

This query is working but the pagination does not work. I am passing the options that I receive from my FlatFeed to do the query in the doFeedRequest, but these options do not paginate

```
<FlatFeed
      feedGroup="timeline"
      options={{
        limit: 20,
        kind: 'like',
        user_id: username,
      }}
      doFeedRequest={async (client, feedGroup, userId, options) => {
  
        const res = await client.reactions.filter(options)
        const results = _.get(res, 'results', [])
        const activitiesIds = _.map(results, v => _.get(v, 'activity_id'))
        const activities = await client.getActivities({ ids: activitiesIds })

        return activities
      }}
/>
```

What would be the correct way to do a timeline only with my "liked" activities (Not only the ones that I am the author, i want all the ones that I have liked)

How can i list items filtered by reactions in FlatFeed with pagination?

**Comment by luisfuertes** [comment]
@jaapbakker88 any idea?

**Comment by luisfuertes** [comment]
Hi?

**Comment by luisfuertes** [comment]
@jaapbakker88 ?

**Comment by jaapbakker88** [comment]
@luisfuertes i've discussed this a bit internally and we've come to the conclusion that our components don't really support this use case right now. But you can make this work by creating a separate feed for your "liked" activities and when you "like" the activity you post the activity to the feed using the `targetFeed` option like so:
```
onToggleReaction(
  'repost',
  activity,
  {},
  { targetFeeds: [`${likedActivitiesFeedGroup}:${userId}`] },
)
```
the onToggleReaction function is should be available on the activity.

**Comment by luisfuertes** [comment]
but in that case the comments reactions of the activities will not be the same as those of the original activity, right?

If it is true, how can i inject "data" prop to FlatFeed to manage queries pagination in my component?

I can get the "client" to make queries like: 
```
const Like = props => {
  return <StreamApp.Consumer>{appCtx => <LikeConsumer {...props} {...appCtx} />}</StreamApp.Consumer>
}
```

But i need insert results in FlatFeed. Can i override "data" prop in flatListProps?

**Comment by luisfuertes** [comment]
@jaapbakker88 any help with this?
