### ISSUE TITLE
Please update to work with Expo Client 39 / React Native 0.63

### ISSUE THREAD

**Issue by tomredman** [GetStream/react-native-activity-feed#154]
**Setup (always fill this in):**

- iOS or Android? iOS
- Expo or regular React Native? Expo
- React Native Version: 0.63.2
- `react-native-activity-feed` or `expo-activity-feed` version: `expo-activity-feed@0.9.1`
- `getstream` version: `getstream@4.5.4`

**Describe the bug**
The default repo no longer runs on Expo Client for iOS, which requires Expo SDK 36, 37, 38, or 39. Attempting to upgrade to 39 results in cascading dependency issues, the biggest being that react native has deprecated `ListView`, and everything fails from there. 

**To Reproduce**

1. Download latest version of Expo client for iOS
2. Try to get this repo to run

**Expected behavior**
The example app runs on Expo.

**Screenshots**

**Additional context**
If I could go back and use an old version of Expo I would, but I can't unfortunately. I will try with Expo 36 as that's the oldest SDK supported by the Expo app.

**Comment by tomredman** [comment]
The offending package was actually `react-native-keyboard-aware-scroll-view`, which needs to be `0.9.2`.

**Comment by Quantmatic** [comment]
> The offending package was actually `react-native-keyboard-aware-scroll-view`, which needs to be `0.9.2`.

Hi Tom, if you managed to get the example to run on the latest expo, I would love to clone your efforts

I'm trying to do the same at the moment, biting through errors

**Comment by vishalnarkhede** [comment]
Hey @Quantmatic @tomredman We will update and fix these issues early next week :)

**Comment by tomredman** [comment]
Thank you @vishalnarkhede! 

Sorry @Quantmatic – I totally missed your comment. My bad!
