### ISSUE TITLE
Date when adding comments is displayed wrong. Makes whole library unusable

### ISSUE THREAD

**Issue by nickjanssen** [GetStream/react-native-activity-feed#156]
**Setup (always fill this in):**
- iOS or Android? both
- Expo or regular React Native? React Native
- React Native Version: 0.63.3
- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`: react-native-activity-feed
- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream` 4.5.4

**Describe the bug**
When adding a comment, the displayed time is one hour ahead. Comments have "in an hour" appended.
![image](https://user-images.githubusercontent.com/2780160/97993563-85d4d900-1de4-11eb-93bb-2568caffa366.png)

**To Reproduce**

1. Live in Belgium
2. Wait until winter (daylight savings must be active)
3. Make a comment

I don't know whether daylight savings have something to do with it, but I'm guessing you guys aren't living here so probably never encountered this. So I'm betting it's the cause.

**Expected behavior**
That the time is displayed right. The text should display "just now" after the comment is made.

**Additional context**
See https://github.com/GetStream/react-native-activity-feed/blob/147af7c9021755fd780021481d32a4b9a4ffae82/src/utils.js#L6

The bug is caused by `humanizeTimestamp` which for some reason appends one hour through `utcOffset()`.

```js
  // Following calculation is based on assumption that tDateTimeParser()
  // either returns momentjs or dayjs object.
  const time = tDateTimeParser(timestamp).add(
    Dayjs(timestamp).utcOffset(),
    'minute',
  ); // parse time as UTC
```

The `timestamp` is already in UTC format so this `.add(` call is unnecessary. Normally I'd make a PR but judging from the number of open PRs and tickets and lack of response I wonder why I even bother making this ticket.

**Comment by hmolotsi** [comment]
@nickjanssen Since the CommentItem class is simple, just create your own and use it instead


```
import {
  Avatar,
  buildStylesheet,
} from 'react-native-activity-feed';
import Moment from 'moment';

class NickCommentItem extends Component {
  render() {
    const { comment, tDateTimeParser } = this.props;
    const styles = buildStylesheet('commentItem', this.props.styles || {});
    return (
      <View style={styles.container}>
        <Avatar source={comment.user.data.profileImage} size={25} noShadow />
        <View style={styles.commentText}>
          <Text>
            <Text style={styles.commentAuthor}>{comment.user.data.name} </Text>
            <Text style={styles.commentContent}>{comment.data.text} </Text>
            <Text style={styles.commentTime}>
              {Moment(comment.created_at).fromNow()}
            </Text>
          </Text>
        </View>
        {this.props.Footer}
      </View>
    );
  }

}
