### ISSUE TITLE
upload image using StatusUpdateForm always fails 

### ISSUE THREAD

**Issue by mm7mod** [GetStream/react-native-activity-feed#160]
**Setup (always fill this in):**

- iOS or Android? android
- Expo or regular React Native? regular React Native
- React Native Version:0.63.3
- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>` 
`-- react-native-activity-feed@0.9.1
- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`
`-- react-native-activity-feed@0.9.1
  `-- react-native-activity-feed-core@0.9.1
    `-- getstream@4.5.4

**Describe the bug**
I have a problem with uploading an image with StatusUpdateForm component
it always gives me : "something went wrong when uploading your image .Is your internet working ? ...etc "

- uploading only text posts work however with images it gives me above error , also small images doesn't work

- the mobile internet is working fine and also trying to use small images as the error suggests but with no luck

![130196981_207050597657735_3972864734010711280_n](https://user-images.githubusercontent.com/46278471/101297645-a43e5200-3832-11eb-806f-7c4ad247979a.jpg)

**To Reproduce**
here is the code :

```
   <StreamApp
        apiKey=""
        appId=""
        token="">
        <FlatFeed Activity={CustomActivity} notify />
        <StatusUpdateForm  feedGroup={"timeline"} />
     
      </StreamApp>
```

**Expected behavior**

Upload image should be successful as both the network and image size are OK .

**Screenshots**
screen shot above

**Comment by mm7mod** [comment]
[Mon Dec 07 2020 03:18:52.544]  WARN     [TypeError: Network request failed]
[Mon Dec 07 2020 03:18:52.572]  WARN     [TypeError: Network request failed]
[Mon Dec 07 2020 03:18:52.573]  WARN     [TypeError: Network request failed]

**Comment by mm7mod** [comment]
[Mon Dec 07 2020 03:18:52.544]  WARN     [TypeError: Network request failed]
[Mon Dec 07 2020 03:18:52.572]  WARN     [TypeError: Network request failed]
[Mon Dec 07 2020 03:18:52.573]  WARN     [TypeError: Network request failed]

**Comment by aamir-ans** [comment]
@mm7mod Is the image upload issue resolved ? I'm facing same issue @vishalnarkhede
