### ISSUE TITLE
IconBadge number doesn't update when notification activities have been read

### ISSUE THREAD

**Issue by Ingibjorg** [GetStream/react-native-activity-feed#17]
**Describe the bug**
The `IconBadge` doesn't update its number after all notification activities have been read.

**To Reproduce**
1. Given that you have rendered the IconBadge component with a custom image component:
```
<IconBadge showNumber>
    <BellImage source={bell} />
</IconBadge>
```
2. Trigger a notification for the user
3. Observe that the IconBadge now displays the number 1
4. Navigate to the notification feed
```
<StreamApp
    style={{ flex: 1 }}
    apiKey={Config.GETSTREAM_API_KEY}
    appId={Config.GETSTREAM_APP_ID}
    userId={userId}
    token={streamToken}
  >
    <NotificationFeed
        userId={userId}
        Group={({ activityGroup }) => <Notification activityGroup={activityGroup} />}
         navigation={navigation}
         options={{ withRecentReactions: true }}
      />
</StreamApp>
```
5. Navigate back to the screen where the IconBadge is and observe that its number still shows 1 and has not been reset to zero. 

**Expected behavior**
As a user, I want to navigate to the NotificationFeed after seeing a number indication on the IconBadge that I have unread notifications. When I navigate back from the NotificationFeed to the previous screen that shows the IconBadge, I expect the IconBadge to show **no number** to indicate that I have no unread notifications.

**Setup:**
 - iOS
- regular React Native
 - React Native Version: 0.57.2
 - `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
yarn list v1.10.1
├─ react-native-activity-feed-core@0.6.8
└─ react-native-activity-feed@0.6.8
 - `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`
yarn list v1.10.1
└─ getstream@3.23.0

**Comment by JelteF** [comment]
To make this work the IconBadge should be a child of the same StreamApp component as the NotificationFeed component. That way they will share the state.

**Comment by Ingibjorg** [comment]
Thanks for clarifying @JelteF!
