### ISSUE TITLE
Image upload always fails in android using StatusUpdateForm component

### ISSUE THREAD

**Issue by aamir-ans** [GetStream/react-native-activity-feed#170]
@vishalnarkhede 
- iOS or Android? android
- Expo or regular React Native? React Native
- React Native Version: 0.62.1
- `react-native-activity-feed` version: 1.0.1
 `npm list --pattern <package-name>
- `getstream` version: 7.2.0

**Describe the bug**
Problem with uploading an image using StatusUpdateForm component.
Always shows popup with error attached screenshot below :
![Screenshot_2021-01-27-23-28-48-95_c06d73ca3bfa20afcf143c32019f8151](https://user-images.githubusercontent.com/64124199/106033244-8fc25b80-60f7-11eb-8015-4dd9225c3414.jpg)

Internet is working fine also checked with multiple small images as well.

**Expected behavior**
Image should upload if size and network is fine.

**Comment by vishalnarkhede** [comment]
@aamir-ans we are working on this issue. Will keep you posted :)

**Comment by aamir-ans** [comment]
@vishalnarkhede Thanks for the update, can you let me know which stable version I can use for now ?

**Comment by aamir-ans** [comment]
@vishalnarkhede Any update or which version I can use for now ?

**Comment by vishalnarkhede** [comment]
@aamir-ans Publishing a patch in hour!!

**Comment by vishalnarkhede** [comment]
@aamir-ans please upgrade to `react-native-activity-feed@1.0.2`.

- Please make sure you have `getstream@7.2.1`  in your yarn.lock or package-lock.json
- Chrome debugger may interfere with network request. So please test upload feature without chrome debugger.

**Comment by aamir-ans** [comment]
@vishalnarkhede Thanks for update.
**StatusUpdateForm** supports multiple image upload or not ?

**Comment by vishalnarkhede** [comment]
@aamir-ans For now, no!!

**Comment by aamir-ans** [comment]
@vishalnarkhede Hey I'm not able to upload an image using **client.images.upload()** function, getting just this error
 **Network Error**. Can you please let me know which getstream version I can use ?

**Comment by vishalnarkhede** [comment]
@aamir-ans Its a well knows issue that Flipper or Chrome debugger interferes will network calls, causing image uploads to fail. So either you should upgrade Flipper to latest version or disable any kind of debugger before testing image uploads

**Comment by vishalnarkhede** [comment]
@aamir-ans please reopen if you are still facing the issue even after disabling debugger!!
