### ISSUE TITLE
<StatusUpdateForm/> bug 

### ISSUE THREAD

**Issue by AlexisJamin** [GetStream/react-native-activity-feed#19]
Related with the `<CommentBox/>` bug, I just found out a bug with `< StatusUpdateForm/>`

I get : 

![img_e3072530e0a6-1](https://user-images.githubusercontent.com/28752161/49509443-af49fa80-f885-11e8-9f22-045a7d7ac748.jpeg)

I have an iPhone 6S. 

I think it's a problem with react-native-sticky-keyboard-accessory package. It does not stick to keyboard. 

EDIT : same bug with my Huawei Y6 2018 : 

![whatsapp image 2018-12-05 at 13 19 14](https://user-images.githubusercontent.com/28752161/49513195-78c5ad00-f890-11e8-86d1-0176d959f42e.jpeg)

**Comment by AlexisJamin** [comment]
Maybe you should update "react-native-sticky-keyboard-accessory": "^0.1.1" to 0.1.2 ?

cf : https://github.com/just4fun/react-native-sticky-keyboard-accessory

**Comment by AlexisJamin** [comment]
I'm using react-navigation : 2.13.0. And createMaterialTopTabNavigator with TabBarPosition: "bottom".

**Comment by JelteF** [comment]
I'm not sure what to do to fix this. It seems more like a bug in the KeyboardAccessory indeed

**Comment by AlexisJamin** [comment]
Yes. Just emailed you. We need to debug at the source. It bugs with react-navigation. 

See snack : https://snack.expo.io/ByDDZv_yN 

And issue : https://github.com/just4fun/react-native-sticky-keyboard-accessory/issues/1

**Comment by JelteF** [comment]
I just released v0.6.16 with the `verticalOffset` prop for StatusUpdateForm: https://getstream.github.io/react-native-activity-feed/#statusupdateform
