### ISSUE TITLE
Invalid userId, please use letters, numbers, - or _: * issue

### ISSUE THREAD

**Issue by SMJ93** [GetStream/react-native-activity-feed#2]
We have managed to get the Sample `StreamApp` working by following the docs:

```
<StreamApp
          apiKey="5rqsbgqvqphs"
          appId="40273"
          token="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZTlkNzc5YzItNTRjMS00NmNhLTg5ZmEtMjg4ZTUzMjgxMDk0In0.Av9dPSVIy2HBm2ep54i69uFQjSOfrAGOZaNbIVghJ1k">
          <FlatFeed
            feedGroup="timeline"
            userId="e9d779c2-54c1-46ca-89fa-288e53281094"/>
</StreamApp>
```

If we use our own credentials like below:

```
<StreamApp
          apiKey={apiKey}
          appId={appId}
          token={token}>
          <FlatFeed
            feedGroup="user"
            userId={userId}/>
</StreamApp>
```

We get the following error:
![screen shot 2018-10-12 at 14 45 27](https://user-images.githubusercontent.com/2145641/46873141-ccd28900-ce2d-11e8-8000-d98cda5f75b0.png)

Even after adding `userId` to the `StreamApp` we still get the error:

```
<StreamApp
          apiKey={apiKey}
          appId={appId}
          token={token}
          userId={userId}/>
```

Are we missing something out?

**Comment by tbarbugli** [comment]
can you console.log all params and make sure that they are what you expect?

**Comment by SMJ93** [comment]
Yup, looks like an issue with the JWT token.

**Comment by JelteF** [comment]
based on the error I would think that the JWT token contains something with weird characters inside the value for `user_id`

**Comment by SMJ93** [comment]
Thanks, @JelteF  fixed now!

**Comment by Juneyoung-Kang** [comment]
@SMJ93 Could you explain how to resolve this issue?

**Comment by SMJ93** [comment]
@Juneyoung-Kang We customised our JWT token. If you use their standard token it works.

**Comment by Juneyoung-Kang** [comment]
@SMJ93 @JelteF Thanks.

**Comment by tlester** [comment]
I'm getting the same issue.  We use auth0 for authentication and they apply a "auth0|" at the top of their id's.  So, I'm getting this error:

Error: Invalid userId, please use letters, numbers, - or _: auth0|60b843b8a6427

How can I resolve this issue?

**Comment by SMJ93** [comment]
@tlester I would open a separate issue - this thread is over 4 years old
