### ISSUE TITLE
Debug problem with redux-saga, redux-navigation, redux

### ISSUE THREAD

**Issue by AugustusCosta** [GetStream/react-native-activity-feed#23]
I only test this in iOS.
React Native project. 

"react": "16.3.1",
"react-native": "^0.56.1",
"redux-saga": "^0.16.2",
"react-navigation": "^2.17.0",
"react-redux": "^5.0.7",
"redux": "^4.0.0",
"react-native-activity-feed": "^0.6.15" , 0.6.14, 0.6.12...

I need to use this like a component in my app and it's not an option for me change the project config.

If I declare any import of react-native-activity-feed at any place (Screen, Component, Util, App...) of my project when I Debug JS Remote all my redux-saga takeLatest methods just stop to work...

```
export function* listWatcherSaga() {
  yield takeLatest(FETCH_ACTION_REQUEST, listWorkerSaga);
}

function* listWorkerSaga(action) {
  const response = yield call(list, action);
  if (response != null) {
    yield put({ type: FETCH_ACTION_SUCCESS, result: response.data });
  }
}

function* list(action) {
  try {
    const response = yield fetch(config.server + '/my_url', {
      method: 'GET',
      headers: { 'Content-Type': 'application/json',
                 'x-access-token': action.data.token
               }
    });
    ....
  } catch (error) {
    ....
  }
}
```

**TypeError: fetch is not a function    at list$.....**

Without Debug JS it's OK.

**Comment by JelteF** [comment]
I just released v0.7.1 and v0.6.18 which fix this problem. Thank you for the clear bug report. Very weird that this only happens when Debug JS Remotely is enabled.
