### ISSUE TITLE
User group feed and instantiating feeds with feed tokens 

### ISSUE THREAD

**Issue by haggalin** [GetStream/react-native-activity-feed#238]
Hi 

Reading the documentation here: 

https://getstream.io/activity-feeds/docs/node/adding_activities/?language=javascript

You can instantiate the feed with a server-side generated feed token. But I can't seem to find a way to use that type token in this package. 

Our use case is to have groups of users which could read and write to the group's feed (identified with the team ID), and it seemed like feed tokens was the way to go, or am I missing something?

**Comment by MartinCupela** [comment]
Hi @haggalin can we close this issue?

**Comment by haggalin** [comment]
Hi yes, I've been chatting with support about this as well and it seems that the use of scoped tokens is not recommended.

Our use case was to have user group feeds which were private for the group members. So for anyone who stumbles on this issue then the recommendation from Stream is described [here](https://getstream.zendesk.com/hc/en-us/articles/1500006211181-How-to-set-up-private-Feed-Groups-with-Stream-Feeds).
