### ISSUE TITLE
FlatFeed options 

### ISSUE THREAD

**Issue by AlexisJamin** [GetStream/react-native-activity-feed#25]
Hi,

I've been trying to use `<FlatFeed/>` option prop to limit the number of posts the user can see.

![capture d ecran 2018-12-23 a 22 23 37](https://user-images.githubusercontent.com/28752161/50387689-23e4bc00-0703-11e9-8672-1df66a61c19a.png)

This does not work. I should see only the 3 last publications right ?

**Comment by JelteF** [comment]
If you provide the `noPagination` prop as well it should work. Otherwise it will simply paginate in batches of 3. https://getstream.github.io/react-native-activity-feed/#!/FlatFeed

**Comment by JelteF** [comment]
I'm not entirely sure what you want then. Either you have pagination and when you scroll down it will show more than 3 activities. Or you don't have pagination and it will show exactly 3 activities

**Comment by AlexisJamin** [comment]
I just want to show an exact number. So it works well. But when I read pagination, for me it creates pages 1-2-3-4 ... and you click on it to see more publications. Maybe it's just a naming issue for me.

**Comment by JelteF** [comment]
The pagination for FlatFeed is infinite scroll based. So when you scroll to the end it will automatically load more items.

**Comment by AlexisJamin** [comment]
Ok I understand. Thanks for your help ! :-)
