### ISSUE TITLE
Viewing other users' feeds

### ISSUE THREAD

**Issue by dolsem** [GetStream/react-native-activity-feed#27]
I am building an app that allows you to open an arbitrary user's profile and view all of their activities, which are added to your timeline feed if you decide to follow them. I can access timeline, but when I try to access user profile it fails with "You don't have permission to do this" error. It seems like the token I generate with my backend (with `client.createUserToken(username)`) only allows the user to access their own feed, not any others. Is there a way around that? Ideally I want to generate a custom token that would give the user read access to their own feed in every feed group, as well as everyone else's feed in a specific feed group (that would be `user` in the react-native-example app). Is there a way to do that? Alternatively, is there a way to give a feed group public read access?

**Comment by JelteF** [comment]
The permissions a user token has are configurable, but by default they should support your use case. 
A user token with user_id 123 can read any feed where the user_id part of the feed `{feed_group}:{user_id}` is 123. And it can also read any feed where the feed group is `user`. I expect you are trying to use a feedgroup named something different than `user` for the profile feed. If you change that to the `user` feed group you shouldn't get the permission error anymore.

Permissions like this can be set up by [support](https://getstream.io/support), so please contact us if you need more feed groups readable/writable by everyone (common cases are a `hashtag` feed group).

**Comment by dolsem** [comment]
Okay, that makes sense. It was indeed different from user. Would be nice to have a feature that lets you make feed groups public or private yourself. Thanks for the response!

**Comment by JelteF** [comment]
Closing this as it's not an issue in the library. If you run into this as well, please contact support and we'll set up the necessary permissions.
