### ISSUE TITLE
Activity object does not contain latest_reactions property

### ISSUE THREAD

**Issue by sksin28** [GetStream/react-native-activity-feed#28]
**Setup (always fill this in):**
 - iOS or Android? Android
-  Expo or regular React Native? React native
 - React Native Version: 0.57.7
 - `react-native-activity-feed` version: 0.8.5
 - `getstream` version: 4.1.0

**Describe the bug**
The `activity` object does not contain `latest_reactions` property. This causes `ReactionList` and `CommentList` components not working. However, the activity contains `own_reactions` property and it contains comments.

Getting the data through `getstream JS` library, the `activity` object does contain `latest_reactions` property.

**To Reproduce**
1. Create a feed
2. Add activities to the feed
3. Add comments to an activity
4. The comment does not appear in the `CommentList` component. During debugging, the `activity` does not contain `latest_reactions` property. 

**Expected behavior**
The `activity` object should contain `latest_reactions` property.

**Comment by sksin28** [comment]
Realized I needed to pass `FeedRequestOptions` in the `FlatFeed` component
```
                options={{
                    withRecentReactions: true
                }}
```
Not sure why this does not default to `true` in [getOptions](https://github.com/GetStream/react-native-activity-feed/blob/b37f3f4c4de1476c70a4d0aa84d9bc7fa217216e/src/Context/Feed.js#L537)

Moreover the [FeedRequestOptions](https://github.com/GetStream/react-native-activity-feed/blob/b37f3f4c4de1476c70a4d0aa84d9bc7fa217216e/custom-definitions/getstream.js#L175)type  does not have the `withReventReactions` property defined,

The documentation can be certainly improved regarding this.

**Comment by JelteF** [comment]
Thanks for the report. I updated the docs to make this behaviour more clear and fixed the mistake in the types. With the next release the docs will be updated automatically on the website.

**Comment by sksin28** [comment]
Thanks @JelteF for the quick response. 👍
