### ISSUE TITLE
StreamContext example

### ISSUE THREAD

**Issue by sksin28** [GetStream/react-native-activity-feed#29]
I'm trying to use `StreamContext` to access the already initialized API client by subscribing to it. But, I'm unable to do so. I tried to follow the example posted in the [Cookbook](https://getstream.github.io/react-native-activity-feed/#cookbook). However, it's not working with an error about `StreamContext`.

Any working example will be really appreciated.

**Comment by JelteF** [comment]
Ah that example is outdated it seems. Instead of `StreamContext.Consumer` you should use `StreamApp.Consumer`.

```
export default class ShareButton extends React.Component {

  render() {
    return (
      <StreamApp.Consumer>
        {(appCtx) => {
          return <ShareButtonInner activity={this.props.activity} {...this.props} {...appCtx} />;
        }}
      </StreamApp.Consumer>
    );
  }

}```

**Comment by sksin28** [comment]
Thanks @JelteF . That works.
Hopefully, we should update the example accordingly.

**Comment by JelteF** [comment]
Yeah I updated the example. Next release will publish the doc update.
