### ISSUE TITLE
How to specify actor attributes?

### ISSUE THREAD

**Issue by hsyyid** [GetStream/react-native-activity-feed#3]
In the code, you reference `actor.data.name`, etc.

I do not see where this is mentioned in the documentation: I tried providing a JSON object when I created the activity too, but it was turned into a string so didn't work either.

Am I missing something? Any help would be appreciated.

https://github.com/GetStream/react-native-activity-feed/blob/master/src/components/Activity.js#L67

If I do it like the documentation, I get an error because it's trying to get `name` from `actor.data` which is `undefined`

```javascript
// Add an activity to the feed
var activity = {actor: 'User:1', verb: 'pin', object: 'Place:42', target: 'Board:1'};

// Asynchronous methods return Promise since v3.0.0
user1.addActivity(activity)
    .then(function(data) { /* on success */ })
    .catch(function(reason) { /* on failure, reason.error contains an explanation */ });
```

**Comment by JelteF** [comment]
Hi, this is now explained here in the docs: https://getstream.io/docs/#frontend_enrichment

**Comment by JelteF** [comment]
I explained it more in #4
