### ISSUE TITLE
Whenever i try to install I get this warning

### ISSUE THREAD

**Issue by Getinwiththem** [GetStream/react-native-activity-feed#34]
**Setup (always fill this in):**

- iOS or Android?
- Expo or regular React Native?
- React Native Version:
- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Getinwiththem** [comment]
Unexpected end of JSON input while parsing near '...egistry.npmjs.org/fs-'

**Comment by JelteF** [comment]
Please fill in the template so we can try to reproduce this. The errer sounds like something is wrong with your npm setup though, not with this library.

**Comment by JelteF** [comment]
Closing this as it is not reproducible.
