### ISSUE TITLE
using targetFeed to notify other users results in "You dont have permission to do this"

### ISSUE THREAD

**Issue by direwolf424** [GetStream/react-native-activity-feed#38]
In Commentbox i am trying to notify users who have been mentioned in the comment.
To do this i am using the `onSubmit` function of the CommentBox.

```
submit(props) {
        if (this.state.commentText != '') {
            props.onAddReaction(
                'comment',
                props.activity,
                {
                    text: this.state.commentText
                },
                { targetFeeds: ['Notification:9a668a1f-ab6d-4263-a7b3-6c0bf26ebd92'] }
            );

            this.setState({ commentText: '' });
        }
    }
```

Now when i am giving user id of a another user stream throws this error
"You don't have permission to do this"

Any help will be really appreciated.

P.S: for now user id is hardcoded.

**Comment by JelteF** [comment]
There's some default permissions for feeds. By default a user can post to any feed where the user_id part in `{feed_group}:{user_id}` is its own id and to any feed where the feed_group part is `notification`. In this case you try to post to `Notification` feed_group (with a capital letter), for a different user_id. So it's not allowed to post there. If you change your feed group to `notification` it should work. [Support](https://getstream.io/support) can modify these permissions for you, if you need any special ones.

**Comment by direwolf424** [comment]
Ohhk @JelteF . I will try and update it here.
Thanks for the quick reply :+1:

**Comment by cbedoy** [comment]
I'm having the same issue but when I want to get a NotificationFeed from user.

```
render() {
      return (
        <NotificationFeed
          feedGroup="notification"
          userId="carlos"
          Group={({ activityGroup, styles, ...props }) => 
            <NotificationsView data={activityGroup}/>
          }
          notify
          navigation={this.props.navigation}
          />
      );
```

Response 
```
Object {
  "code": null,
  "message": "You don't have permission to do this",
  "params": Array [],
}
```
