### ISSUE TITLE
The REST API returns actor as type string, but the Activity component expects an object

### ISSUE THREAD

**Issue by SMJ93** [GetStream/react-native-activity-feed#4]
In the REST API docs it expects actor to be of type string: https://getstream.io/docs_rest/#activity

But in the react-native-activity-feed `Activity` component it is expecting an object with the following structure:

https://getstream.github.io/react-native-activity-feed/#activity

```
data: {
  name: string,
  profileImage: string
}
```

Is this a bug?

**Comment by tbarbugli** [comment]
The React Native components use data enrichment to store objects in the actor and object field. You can find more information about that here: https://getstream.io/docs/#frontend_enrichment

**Comment by SMJ93** [comment]
Ahhhh, I didn't see that! Thanks for the quick response

**Comment by SMJ93** [comment]
@tbarbugli, sorry I am finding the docs very confusing:

> When using Stream on the backend "Enrichment" is relatively simple to implement yourself. First you read the feed from Stream. Then you find all references and retrieve them from your database. You could do the same on the frontend as well, but this would require you to do an extra request to your own backend to return the actual objects based on the reference. However, this is not needed because Stream allows you to do automatic enrichment when reading feeds using the frontend APIs.

Specifically `However, this is not needed because Stream allows you to do automatic enrichment when reading feeds using the frontend APIs`. How does this work?

We are still getting the actor `user:ed` back. Do you have a react-native enrichment example we could refer to?

Thanks

**Comment by JelteF** [comment]
You should not use `user:ed` as an actor, instead you should:
- on the frontend use a User instance: https://getstream.io/docs/#frontend_user_enrichment
- on the backend use a User reference: https://getstream.io/docs/#frontend_backend_references

Note: It's important to actually add the data to the "user" collections like shown in those examples:
- on the frontend use userSession.user.add({name: "SMJ93"})
- on the backend use client.collections.upsert({id: userId, name: 'SMJ93'})
