### ISSUE TITLE
CommentList not updating in realtime when oldestToNewest is set

### ISSUE THREAD

**Issue by dormied** [GetStream/react-native-activity-feed#43]
**Setup (always fill this in):**

- iOS or Android? ios
- Expo or regular React Native? expo

- React Native Version: expo-activity-feed@0.8.8
getstream version:  getstream@4.2.1

**Describe the bug**
When setting oldestToNewest to true in CommentList, the comments don't update instantly when adding a new comment

**To Reproduce**
Add oldestToNewest to a commentlist
add a comment with commentbox
pull down to refresh to see the comment

**Expected behavior**
The comment should automatically update in the CommentList without having to pull down

**Comment by dormied** [comment]
I just set infiniteScroll and reverseOrder to work around this, but bug still remains

**Comment by cbedoy** [comment]
I had the same issue.

**Comment by jaapbakker88** [comment]
The solution is to use reverseOrder. The way our api works makes it hard to paginate in reverse and I think this is the best solution.
