### ISSUE TITLE
StatusUpdateForm and modifyActivityData / defaultUserData prop

### ISSUE THREAD

**Issue by AlexisJamin** [GetStream/react-native-activity-feed#48]
**Setup (always fill this in):**

- iOS & Android
- Expo : v32.0.0
- React Native Version: "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
- `expo-activity-feed` version: v. 0.8.9
- `getstream` version: none

**Describe the bug**
I'm using `StatusUpdateForm` to post on my feed. I want to add the user's name and its picture. I use the prop `modifyActivityData ` but I get an Alert "You don't have the permission to do this".

**To Reproduce**

![Capture d’écran 2019-06-12 à 16 49 59](https://user-images.githubusercontent.com/28752161/59361485-3941b700-8d32-11e9-8a2a-320fa5cc58fe.png)

**Expected behavior**
It should add a picture and a name to the user to be shown in the Activity.

**Screenshots**
![IMG_0673](https://user-images.githubusercontent.com/28752161/59361282-e5cf6900-8d31-11e9-94bb-e5b64a41d52c.PNG)

**Comment by AlexisJamin** [comment]
EDIT:

I tried to use `defaultUserData` prop like in https://github.com/GetStream/react-native-example/blob/master/App.js but it does not work either ... It still show "Unknown". Please help ! :)

![Capture d’écran 2019-06-17 à 15 54 58](https://user-images.githubusercontent.com/28752161/59609864-7e8e2c00-9118-11e9-95d2-770a92896549.png)

![WhatsApp Image 2019-06-17 at 16 31 41](https://user-images.githubusercontent.com/28752161/59612601-a59b2c80-911d-11e9-8a37-9cbde270482f.jpeg)

**Comment by jaapbakker88** [comment]
Hi @AlexisJamin, for any other people running into this issue, did you manage to get it fixed?

**Comment by DaniloArantesF** [comment]
> Hi @AlexisJamin, for any other people running into this issue, did you manage to get it fixed?

I'm having the same issue.  Tried modifyActivityData too.

**Comment by Muffles** [comment]
Any update on this? Can't seem to shake off the "Unknown" user as well...

**Comment by animmore** [comment]
@AlexisJamin Have you fixed it?
