### ISSUE TITLE
I need to ask

### ISSUE THREAD

**Issue by Recave** [GetStream/react-native-activity-feed#49]
The StreamApp should I create a new folder or rename the APP.js? Also, I should find my own platform for this right? 

**Also these**
<StreamApp
  apiKey="{API_KEY}"
  appId="{APP_ID}"
  userId="{USER_ID}"
  token="{TOKEN}"
  analyticsToken="{ANALYTICS_TOKEN}"
>
  {/* everything from your application interacting with Stream should be nested here */}
</StreamApp>

const client = stream.connect(
  API_KEY,
  API_SECRET,
);
const userToken = client.createUserToken(userId);
console.log(userToken);

const client = stream.connect(
  API_KEY,
  API_SECRET,
);
const analyticsToken = client.getAnalyticsToken();
console.log(analyticsToken);

**Comment by tbarbugli** [comment]
https://getstream.io/react-native-activity-feed/tutorial/
