### ISSUE TITLE
TypeError: getActivityPath is not a function

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#50]
**Setup (always fill this in):**

- iOS and Android
- React Native
- React Native Version: 0.59.5
- └─┬ react-native-activity-feed@0.8.9
  └─┬ react-native-activity-feed-core@0.8.9
    └── getstream@4.2.2 

**Describe the bug**
Unhandled JS Exception: TypeError: TypeError: getActivityPath is not a function. (In 'getActivityPath(activityId)', 'getActivityPath' is undefined)

**Code**
```
<StreamApp
                    apiKey=""
                    appId=""
                    userId={userId}
                    token={UserToken}
                    analyticsToken={AnalyticsToken}>
                    <CommentList
                        activityId={props.activityId}
                        props
                    />
                </StreamApp>
```
**Expected behavior**
Have to list all the comments for that particular post

**Comment by aldrinc** [comment]
@jamesawer3 How did you resolve this issue? I'm having the same issue when I'm trying to show the comment list on a different page outside of the SinglePost component. I tried passing the props using react navigation but I still get this error.

**Comment by jamesawer3** [comment]
I used [SinglePost](https://getstream.github.io/react-native-activity-feed/#singlepost) for displaying comments. Try that!!!

**Comment by Shomari** [comment]
@aldrinc any luck with this error without using SinglePost?  I'm having the same issue

**Comment by jaapbakker88** [comment]
@aldrinc @Shomari can you tell me a bit more about your setup.

**Comment by Shomari** [comment]
@jaapbakker88 basically I have a flatfeed with a custom activity.  In that custom activity if you click on a post I use the react navigator to take you to a screen with only that post and pass params in.  I wanted a bit more of a customized look so I'm not really using the single post component (although I'm not totally against it).  

In the single post screen, I have an Activity component inside a StreamApp component with my apps info in it.  Inside that activity component I have a LikeButton in which I pass in props and works fine.  However if I add in CommentList and pass in props I get the error.  All activity information is included in the props that i'm passing in.  

Looking at the source code, it appears that the props from appctx aren't being passed into the ReactionList component that CommentList is using.  I don't really know why that is.

**Comment by jaapbakker88** [comment]
I think the problem is your usually getting a bunch of props passed through from either the FlatFeed or the SinglePost. If you don't use these components you're missing some functionality the CommentList depends on. But you can customize your activity completely with the SinglePost or FlatFeed components by passing your own component like this <SinglePost Activity={YourComponent} />, this should give you access to all the props you might need.
