### ISSUE TITLE
Failed to authenticate when adding `notify` to FlatFeed or NotificationFeed

### ISSUE THREAD

**Issue by SMJ93** [GetStream/react-native-activity-feed#6]
We've managed to get both the FlatFeed and NotificationFeed working with our custom schema:

<img width="390" alt="screenshot 2018-10-25 at 14 44 12" src="https://user-images.githubusercontent.com/2145641/47505041-3fe3f280-d865-11e8-8fef-871ef79de3e2.png">

If we add the prop `notify` to the `NotificationFeed` component we get the following error:

<img width="388" alt="screenshot 2018-10-25 at 14 51 26" src="https://user-images.githubusercontent.com/2145641/47505208-a23cf300-d865-11e8-9562-31d42fa95019.png">

The only change is the `notify` flag, is there something else we need to do?

**Comment by tschellenbach** [comment]
@JelteF and @thesyncim

**Comment by JelteF** [comment]
Did you double check the appId prop that you provided to StreamApp? Also can you share the code you use for the NotificationFeed?

**Comment by jaapbakker88** [comment]
hey @SMJ93, I've not been able to reproduce your issue with the notify prop in my environment with my example tag. Could you [email](mailto:jaap@getstream.io) me the code with the filled in credentials of your app so I can test it with in my own example app.

About the bell icon and the other issues. We're still improving the documentation, but we have an example app where we've done most of these ourselves which you mind find helpful to look at. We have an [IconBadge](https://getstream.github.io/react-native-activity-feed/#iconbadge) component that adds a red badge(with or without number) to an icon you provide.

Example app: [https://github.com/GetStream/react-native-activity-feed](https://github.com/GetStream/react-native-activity-feed)

**Comment by tschellenbach** [comment]
@SMJ93 cool to see your progress, what sort of app are you working on?

**Comment by SMJ93** [comment]
Thanks @jaapbakker88, i've sent you an email. Let me know if you need anything else.

@tschellenbach a deals and recognition app 😃

**Comment by SMJ93** [comment]
Managed to fix this thanks to @jaapbakker88's help!

If anyone else encounters a similar problem, make sure you are setting the correct data in your JWT token.

We were sending `resource` and `action` from the frontend along with the incorrect `user_id`.
