### ISSUE TITLE
UI Customisation for feed

### ISSUE THREAD

**Issue by emvigotech** [GetStream/react-native-activity-feed#67]
**Setup (always fill this in):**

- iOS or Android? iOS
- Expo or regular React Native? React Native
- React Native Version: 0.58.6
- `react-native-activity-feed` version:   "react-native-activity-feed": "^0.8.9",

**Describe the bug**
I want to customize the feed 
1.I want make spacing between the feeds.
2.Make Feed corner rounded
2.Changing Like and comment icon

![F67A2F77-D810-42E5-93A0-1183623D0B68](https://user-images.githubusercontent.com/26790656/62949978-d9848c80-be04-11e9-84d2-b7b9c3c6bd9a.jpg)

Please advise a way to make the changes like this
Thanks in Advance

**Comment by jaapbakker88** [comment]
Hi @emvigotech, if the above image is what you want it to look like I think the best way for you to realize that is using your own custom Activity component. You can make use of our components like this:

```
<FlatFeed 
   {...yourprops}
   Activity={(props) => ( 
       <Activity
            Header={yourheader}
            Content={yourcontent}
            Footer={yourfooter}
       />
   )}
/>
```

I think this is the easiest way for you to realise something like you're trying to do in the above image.

**Comment by cbedoy** [comment]
In my case I'm using 

```
render() {
    return (
      <FlatFeed
        feedGroup="user"
        userId={Global.getUser()}
        Activity={(props) =>
          <TouchableHighlight onPress={() => this.onClick({ ...props })}>
            <FeedActivity {...props} />
          </TouchableHighlight>
        }
        navigation={this.props.navigation}
        notify
        />
    );
  }
```

And

```
const FeedActivity = (props) => {

  let type = props.activity.verb;
  let contentView
  if (type === 'resource'){
    contentView = <LinkContentView {...props} />
  }else{
    contentView = <ContainerView {...props} />
  }

  return (
    <View>
      <ExplorerHeaderView {...props} />
      <ContentView {...props}/>
      {contentView}
      <ReactionsView {...props} />
      <DividerView />
    </View>
  );
}
```
