### ISSUE TITLE
expo-activity-feed@0.8.11 breaks the app

### ISSUE THREAD

**Issue by dolsem** [GetStream/react-native-activity-feed#68]
**Setup (always fill this in):**

- iOS or Android? iOS
- Expo or regular React Native? Expo
- React Native Version: 0.59.8
- `react-native-activity-feed` or `expo-activity-feed` version: 0.8.11
- `getstream` version: 4.2.5

**Describe the bug**
Metro Bundler fails to build the bundle with error:
```
ENOENT: no such file or directory, scandir '/path/to/app/node_modules/react-native-activity-feed-core/lib/images'
```

**To Reproduce**
Update to `expo-activity-feed` version 0.8.11.

**Expected behavior**
Building the bundle should have succeeded.

**Comment by jaapbakker88** [comment]
@dolsem, which version of Expo are you using? In the meantime can you try using version 0.8.9, maybe we broke something recently.

**Comment by jaapbakker88** [comment]
@dolsem The issue was with our release script. I just release version `0.8.13` which should resolve this issue.

**Comment by dolsem** [comment]
@jaapbakker88 just tried version `0.8.13` and it still has the same problem for me. Yet version `0.8.9` works fine, you're right. I am using Expo SDK 33.

**Comment by jaapbakker88** [comment]
Alright thank you, I will run some test to see where this is coming from. For now you can use `0.8.9` unless you're using multiple CommentLists within one screen.

**Comment by jaapbakker88** [comment]
@dolsem could you try `0.8.14`

**Comment by dolsem** [comment]
@jaapbakker88 yes, it works, thank you!
