### ISSUE TITLE
How's timeline follow works.

### ISSUE THREAD

**Issue by cbedoy** [GetStream/react-native-activity-feed#69]
Hi everyone.

Given we discovered we didn't have support from native code in Android about real time. We had to move react native library.

About follow feeds we have doing with Kotlin:

```
 val timeline = StreamUtil.flatFeed("timeline",  "User One")
        users.forEach { userName ->
            val feed = StreamUtil.flatFeed("user", userName)
            timeline.follow(feed).get()
 }

return timeline.getEnrichedActivities(
            Limit(25),
            EnrichmentFlags()
            .withRecentReactions()
            .withReactionCounts()).get()

```
_Given **User One** I followed a list or users and put on a **timeline** FlatFeed_

https://github.com/cbedoy/Stream-Client/blob/master/app/src/main/java/cbedoy/streamclient/explorer/ExplorerRepository.kt#L11

Currently we're using this code for retrieve a FlatFeed from given **userId**.

```
return (
      <FlatFeed
        feedGroup="user"
        userId={Global.getUser()}
        Activity={(props) =>
          <TouchableHighlight onPress={() => this.onClick({ ...props })}>
            <FeedActivity {...props} />
          </TouchableHighlight>
        }
        navigation={this.props.navigation}
        notify
        />
    );
```

I'd like to know how it could apply for a **<FlatFeed  />** such as Timeline FlatFeed, given your documentation you have :

https://getstream.github.io/react-native-activity-feed/#!/FlatFeed

Where's not specify how I could follow multiple and not one userId.

**Comment by jaapbakker88** [comment]
@cbedoy I think you should not use `feedGroup="user"` but `feedGroup="timeline"`. The user feedGroup is just the users activities. Where the timeline is a timeline with the activities of all the people you follow. Let me know if that solves your issue.

**Comment by rafaelcavalcante** [comment]
Hi @jaapbakker88. Im not able to see the post from people i follow. I'm using the component like this:

`<FlatFeed feedGroup="timeline" Activity={CustomActivity} notify />`

I was wondering if you can't make the doc a little more friendly, like this:

![00001](https://user-images.githubusercontent.com/405355/67957403-50dfe600-fbd4-11e9-90b4-04f2d359f0ad.png)
