### ISSUE TITLE
how to refresh comment list when update reaction

### ISSUE THREAD

**Issue by ThanhNghia944** [GetStream/react-native-activity-feed#77]
**Setup (always fill this in):**
i use CommentList to show comments 
If I use props.onAddReaction then the commentList will automatically refresh
but when I update the comment I use client.reactions.update (reactionId, data);
then the commentList is not automatic refresh

**Comment by jaapbakker88** [comment]
We don't support realtime updates for reactions right now, so that's why we don't support it updating automatically.

**Comment by ThanhNghia944** [comment]
pls for me know how to refresh it through props if i use commentList or SinglePost
thank you very much

**Comment by jaapbakker88** [comment]
Right now it doesn't support this. Our CommentList supports all flatList props so you could try setting onRefresh to reload the current page.

https://getstream.github.io/react-native-activity-feed/#!/CommentList
https://facebook.github.io/react-native/docs/flatlist#onrefresh

**Comment by ThanhNghia944** [comment]
thank you very much ^^

Vào Th 3, 10 thg 9, 2019 vào lúc 15:39 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by hitachiSasuke** [comment]
hi jaapbakker88 can you for me example use flatList props to refresh I use 
 flatListProps={{
                      //  onRefresh:this._onRefesh,
                       ItemSeparatorComponent: this._renderSeparator,
                      //  refreshing:this.state.isRefreshing,
                         extraData:this.state,
                       removeClippedSubviews:true,
                       keyExtractor: this._keyExtractor,
                      // refreshControl:this._refreshControl
                    }}
but don't work

**Comment by jaapbakker88** [comment]
@ThanhNghia944 how did you solve this issue. @hitachiSasuke I haven't actually tried this myself but adding the onRefresh prop it should give you a pull to refresh to refresh the comment list.

**Comment by ThanhNghia944** [comment]
Sorry, I am still researching :((

Vào Th 4, 11 thg 9, 2019 vào lúc 15:57 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by hitachiSasuke** [comment]
Hix onRefresh how to refresh it, I lost the whole day, but still couldn't refresh
can you for me example onRefresh, thank you 🙏

**Comment by jaapbakker88** [comment]
I don't have an example as I haven't done this myself. This should work as a pull to refresh.

**Comment by hitachiSasuke** [comment]
hi jaapbakker88 if I use onRefresh will call get data to refresh current page from API but I use commentList from react native feed activity so i don't know how to get data to  refresh

**Comment by hitachiSasuke** [comment]
for example :   refreshing={this.state.isFetching} and onRefresh() {
     this.setState({ isFetching: true }, function() { this.getApiData() });
  } 
this.getApiData i don't know when I use commentList

**Comment by Kushpakistan** [comment]
same issue this is a bug

**Comment by hitachiSasuke** [comment]
hi jamesawer3 what is strings['LoaderDeletingComment'] ? 
can you explain for me

**Comment by ThanhNghia944** [comment]
jamesawer3  how to refresh ???

**Comment by jamesawer3** [comment]
@hitachiSasuke That is the message which will be displayed when the page is loading

**Comment by jamesawer3** [comment]
@ThanhNghia944 just check [react-native-spinkit](https://github.com/maxs15/react-native-spinkit) for loading a page or you can any npm's for making the page to load.

**Comment by hitachiSasuke** [comment]
@jamesawer3 I  do not understand how to refresh the page when updating the comment rather than removing the comment (because remove has realtime to automatically refresh the page)

**Comment by jamesawer3** [comment]
@hitachiSasuke For me it didn't refresh in [SinglePost](https://getstream.github.io/react-native-activity-feed/#singlepost) so i added a loader in that screen

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  can you write props when update comment or activity i will call it to update current page (screen)

**Comment by jaapbakker88** [comment]
Hi @ThanhNghia944  how would I know when you call update?

**Comment by ThanhNghia944** [comment]
you can for me props when i call update
ex: props refreshComment with ref  = 'comment'
and i will call this.comment.refreshComment -> auto refresh update data (
same TextInput when i call this.textInput.focus() )
or in commentList props.refresh() i will call to update data

Vào Th 6, 13 thg 9, 2019 vào lúc 22:00 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by Kushpakistan** [comment]
hope
jaapbakker88
jaapbakker88

Vào Th 6, 13 thg 9, 2019 vào lúc 23:25 ThanhNghia944 <
notifications@github.com> đã viết:

**Comment by hitachiSasuke** [comment]
@jaapbakker88  Please help us ....

**Comment by ThanhNghia944** [comment]
@jaapbakker88  can you help me how to refresh

**Comment by ThanhNghia944** [comment]
similar to how to refresh activity after update 
<img width="444" alt="Screen Shot 2019-09-19 at 9 07 35 AM" src="https://user-images.githubusercontent.com/53257922/65207748-f32c8a00-dabc-11e9-9884-c2667ce5efec.png">

**Comment by ThanhNghia944** [comment]
i have   flatListProps={{
          ListEmptyComponent: this._renderListEmptyComponent
          ItemSeparatorComponent: this._renderSeparator,
          extraData:this.state.refresh,
        }}
Based on extraData: this.state.refresh when I press a button will change the state refresh to flatlist refresh again, but it does not work.

**Comment by ThanhNghia944** [comment]
or flatListProps={{
          ListEmptyComponent: this._renderListEmptyComponent
          ItemSeparatorComponent: this._renderSeparator,
          refreshing:this.state.refresh,
          onRefresh:this.onRefresh
        }}
then it shows loading, but how does the loading end (setState false) to update the data when I use FlatFeed

**Comment by ThanhNghia944** [comment]
Sorry but I did everything, but still cannot refresh, hope you help

**Comment by jaapbakker88** [comment]
Sorry I don't have a solution for this myself. The library doesn't support it yet and I'm not sure when we're going to get around to implementing this functionality.

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  you can for me ref = {this.comment.}  and i will call this.comment.refreshComment -> it will call refreshComment()  -> refresh page current
pls help me

**Comment by ThanhNghia944** [comment]
please help me

**Comment by jaapbakker88** [comment]
Sorry, we don't support this yet and I don't have the time to look into this right now. If you can explain a simple solution to this problem I can have a look but right now your suggestions don't make sense to me. Also please keep this discussion in this issue and don't post in other issues. If something is really urgent, this is open source so you can always open a PR and I will have a look there.

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  thank you for support

**Comment by kathirsuresh** [comment]
If you remove the 
line no 76  : if (!oldestToNewest) {
line no 77:      return;
line no 78    }
in 
react-native-activity-feed/src/components/ReactionList.js 

And try it, the comment list automatically updated
