### ISSUE TITLE
How to handle the hashtag press in feed??

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#78]
Hi,
 When I'm pressing the hashtag which is coming in activity feed, I have to navigate it to another page. Can someone help me with this??? As of now if a press the hashtag it's just printing the value's of that particular hashtag

**Comment by ThanhNghia944** [comment]
hi you can use 
 const parseFormat = [
        { type: 'url', style: styles.url, onPress: this.handleUrlPress },
        { type: 'email', style: styles.email, onPress: this.handleEmailPress },
        { pattern: /#(\w+)/, style: styles.hashTag ,onPress: this._handleTag}
    ]
 <ParsedText
            style={styles.text}
            parse={parseFormat}
          >{text}
          </ParsedText


---with ParsedText from import ParsedText from 'react-native-parsed-text';

**Comment by jamesawer3** [comment]
Thanks for your reply @ThanhNghia944. Can you please tell how to parse the text which is coming in [Activity](https://getstream.github.io/react-native-activity-feed/#activity) props?

**Comment by jaapbakker88** [comment]
@jamesawer3 this is currently not built in yet. I'll add it to my list of things to update for next week.

**Comment by jamesawer3** [comment]
@jaapbakker88 Thank you for your response kindly update it sooner. Waiting for your response

**Comment by jaapbakker88** [comment]
@jamesawer3 I updated the library to version `0.8.16` which gives you access to the following props:

- `onPressMention(text, activity)`
- `onPressHashtag(text, activity)`

**Comment by jamesawer3** [comment]
@jaapbakker88 Thanks for the update will check it and revert you back

**Comment by jamesawer3** [comment]
@jaapbakker88 Should we pass the text and activity to that function??? Can you please give an example how to access??

**Comment by jaapbakker88** [comment]
the prop should be a function and that function has access to text(the clicked text), and the activity.

<Acitvity 
onPressHashtag={(text, activity) => console.log(text, activity)}
/>

**Comment by jamesawer3** [comment]
@jaapbakker88 Thank you so much it's working fine

**Comment by jamesawer3** [comment]
Have an another doubt, Is there a way to access the string after space

#String is correctly working but

#strings space is not working.

**Comment by jaapbakker88** [comment]
No that's not possible at the moment. Because we would have no idea when to stop the hashtag. Hashtags usually don't have spaces.

**Comment by jamesawer3** [comment]
Okay thank you for your response

**Comment by ThanhNghia944** [comment]
^^thank you lib jaapbakker88
