### ISSUE TITLE
LoadMoreButton not use in CommentList

### ISSUE THREAD

**Issue by ThanhNghia944** [GetStream/react-native-activity-feed#79]
Hi ! 👋 
i used LoadMoreButton in CommentList but LoadMoreButton not use and  when i check props of CommentList and ReactionList do not use props LoadMoreButton , please help me ! 
<CommentList
                    {...props}
                    flatListProps={{
                       ItemSeparatorComponent: this._renderSeparator
                    }}
                    activityId={(props.activity || {}).id}
                    reverseOrder
                    oldestToNewest ={false}
                    infiniteScroll={false} //show ButtonLoadmore
                    LoadMoreButton={do not use   }

**Comment by ThanhNghia944** [comment]
<img width="1070" alt="Screen Shot 2019-09-13 at 5 03 10 PM" src="https://user-images.githubusercontent.com/53257922/64854791-b12cbf80-d648-11e9-8f60-26cc61c3c892.png">
-- | -- | -- | --
doc  : 
infiniteScroll | boolean | false | If the CommentList should paginate when scrolling, by default it shows a "Load more" button
-- | -- | -- | --
how to custom UI  "Load more" button

**Comment by jaapbakker88** [comment]
This should do the trick: `<CommentList LoadMoreButton={YourLoadMoreButtonComponent} />`

**Comment by ThanhNghia944** [comment]
Hi @jaapbakker88  please check props LoadMoreButton in CommentList,
when i check props of CommentList and ReactionList do not use props LoadMoreButton I think this is bug
Code
  <CommentList
                    {...props}
                    flatListProps={{
                       style: {
                       }, 
                       ItemSeparatorComponent: this._renderSeparator,
                    }}
                    activityId={(props.activity || {}).id}
                    reverseOrder
                    oldestToNewest ={false}
                    infiniteScroll={false} //false: shows a "Load more" button 
                    LoadMoreButton={<LoadMoreButton />}

with 
LoadMoreButton
export default class LoadMoreButton extends React.Component {
  static defaultProps = {
    children: 'Load more Test',
  };

  render() {
    const { children, refreshing, onPress } = this.props;
    const styles = buildStylesheet('loadMoreButton', this.props.styles);
    return (
      <TouchableOpacity
        style={styles.button}
        onPress={onPress}
        disabled={refreshing}
      >
        <Text style={styles.buttonText}>{children}</Text>
      </TouchableOpacity>
    );
  }
}
<img width="367" alt="Screen Shot 2019-09-13 at 7 13 14 PM" src="https://user-images.githubusercontent.com/53257922/64861605-8e0b0b80-d65a-11e9-838b-b4ad8e34334e.png">
please help me

**Comment by jaapbakker88** [comment]
Hi @ThanhNghia944 you're right. The prop wasnt passed through. I fixed this in version `0.8.6`

thanks

**Comment by ThanhNghia944** [comment]
Thanks for the update ^^

**Comment by ThanhNghia944** [comment]
Thank you so much it's working fine ^^
