### ISSUE TITLE
Pressing on Notifier renders a blank screen

### ISSUE THREAD

**Issue by Ingibjorg** [GetStream/react-native-activity-feed#8]
If a user scrolls down the activity feed, then gets a notification that a new activity is available and clicks on it, the feed renders as a blank screen. If you scroll down on the blank screen, the feed appears again.

**Steps to reproduce**
1. Scroll down the activity feed
2. Wait for a new item to be added to the feed
3. Click on the notifier that is displayed:
![simulator screen shot - iphone x - 2018-11-01 at 13 21 30](https://user-images.githubusercontent.com/5962836/47878608-f737b680-dddb-11e8-9043-3fb8a47ef179.png)
4. Observe that the feed becomes blank: 
![simulator screen shot - iphone x - 2018-11-01 at 13 21 32](https://user-images.githubusercontent.com/5962836/47878700-277f5500-dddc-11e8-8499-fb2ab4dd06ca.png)
5. If you scroll down the blank screen again, the feed appears.

My project is using React Native 0.57.1 and was initialized with `react-native init`.

**Comment by tschellenbach** [comment]
Hi there, this is a bit hard to debug without the underlying JS error. Do you have a stack trace about this error?

**Comment by Ingibjorg** [comment]
@tschellenbach thanks for replying. There is no JS error here. It just looks like clicking on the notifier causes the view to scroll way too far up so it renders a white screen. If I scroll down a bit, the feed gets positioned correctly on the screen again.

**Comment by tschellenbach** [comment]
Jelte will help out with this, what sort of app are you working on?

**Comment by Ingibjorg** [comment]
Thanks @tschellenbach. It's a charity based app.

**Comment by JelteF** [comment]
@Ingibjorg I wasn't able to reproduce this exact issue, but I did find an issue with scrolling to the top not always working. I fixed that now in release 0.6.7 and I think it could be the root cause for your issue as well. Could you try it out and let me know if this is now fixed for you?

**Comment by Ingibjorg** [comment]
Thank you so much for the quick fix @JelteF ! It's working as expected now.
