### ISSUE TITLE
Bug When Likecomment

### ISSUE THREAD

**Issue by ThanhNghia944** [GetStream/react-native-activity-feed#82]
Hi @jaapbakker88  
I like a comment that shows the correct list of latest_children, own_children like and number of likes but when I refreshed, own_children is empty.
now I continue to like that comment, but children_counts + 1 without resetting my likes (like like activity)
 first like
<img width="383" alt="Screen Shot 2019-09-16 at 2 26 35 PM" src="https://user-images.githubusercontent.com/53257922/64940415-1a514480-d88e-11e9-8ad6-36e6a476fc5e.png">

after refresh 
<img width="398" alt="Screen Shot 2019-09-16 at 2 27 46 PM" src="https://user-images.githubusercontent.com/53257922/64940439-2d641480-d88e-11e9-9731-b95bbec8dd67.png">

and like again
<img width="372" alt="Screen Shot 2019-09-16 at 2 28 20 PM" src="https://user-images.githubusercontent.com/53257922/64940466-4076e480-d88e-11e9-8fd7-ff578558b8b3.png">

Code:
 let isExitsUser = false;
  const own_children = (comment.own_children || {}).like || [];
  if (own_children && own_children.length) {
    isExitsUser = true;
  }
and props 
props.onToggleChildReaction(AppConfig.VERB_LIKE, comment, {}, {});

**Comment by jaapbakker88** [comment]
In your feed options on FlatFeed or SinglePost you want to set `withOwnChildren` to `true`.  This is makes sure you load the childReactions on initial load. 

```
<SinglePost
    options={{
        withOwnChildren: true,
    }}
/>
```

**Comment by jamesawer3** [comment]
@ThanhNghia944 Can you please tell me how you brought that posted time, like and comment below the comment list???

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  thank you when i set  withOwnChildren: true in SinglePost solved the like issue
but There is a new problem
When I comment the child after I refresh it it is duplicated twice and I cannot see other people's comments
<img width="393" alt="Screen Shot 2019-09-16 at 3 06 24 PM" src="https://user-images.githubusercontent.com/53257922/64942555-913d0c00-d893-11e9-8185-406df8403e03.png">
<img width="387" alt="Screen Shot 2019-09-16 at 3 08 45 PM" src="https://user-images.githubusercontent.com/53257922/64942685-e711b400-d893-11e9-8e7e-53e6d2e9d2b1.png">
If I set withOwnChildren: false, it's ok ( but like like error at first)
<img width="384" alt="Screen Shot 2019-09-16 at 3 10 57 PM" src="https://user-images.githubusercontent.com/53257922/64942796-348e2100-d894-11e9-8a87-19d84fdb1d5b.png">
code
comment child 
 this.setState({
      dataCommentChild: ( (comment.latest_children || {}).comment || [] )
    });

**Comment by ThanhNghia944** [comment]
hi jamesawer3 i custom commentlist with 
 CommentItem={({ comment }) => {
                      return (
                        <React.Fragment>
                          <CommentItemCustom 
                               onShowModallize={this._onShowModallize}
                               onPressCommentChild = {this._onPressCommentChild}
                               onPressCommentChildParent = {this._onPressCommentChildParent}
                               onPressEditComment = {this._onPressEditComment}
                               onRemoveChildReaction = { (commentParent, idChildReaction) => {
                                props.onRemoveChildReaction(AppConfig.VERB_COMMENT, commentParent, idChildReaction);
                               }}
                               props = {props}
                               userIdCurrent= {this.state.userId}
                               comment={comment} />
                        </React.Fragment>

                      );
                    }}

**Comment by jamesawer3** [comment]
@ThanhNghia944 CommentItemCustom is your own custom component where you have coded right???

**Comment by ThanhNghia944** [comment]
yes CommentItemCustom full code for you 
render() {
    const { comment = {}, props, userIdCurrent ,onShowModallize =() => {}} = this.props;
    let text = _.get(comment.data, 'text', '');
    text = text.trim();
    const children_counts = (comment.children_counts || {}).comment || 0;
    let label_children = '';
    if (children_counts > 0 &&
      (comment.latest_children || {}).comment &&
      (comment.latest_children || {}).comment.length > 0
    ) {
      let itemFirst = (comment.latest_children || {}).comment[0] || {};
      label_children = _.get(itemFirst.user, 'data.name');
    }
    const userIdComment = _.get(comment.user, 'id');
    return (
      <View style={styles.container}>
        <View style={styles.viewHeader}>
          <TouchableOpacity
            disabled={userIdCurrent === userIdComment ? false : true}
            activeOpacity={0.6}
            onLongPress={this._handlerLongClick}
          >
            <View style={{ flexDirection: 'row' }}>
              <FastImage
                style={styles.imageView}
                resizeMode={FastImage.resizeMode.cover}
                source={
                  _.get(comment.user, 'data.profileImage')
                    ? UtiImage.getLink(comment.user.data.profileImage)
                    : require('../../../assets/imgs/accnt_avatar_defaut.png')
                }
              />
              <View style={styles.viewAuthor}>
                <Text style={styles.commentAuthor}>{_.get(comment.user, 'data.name', '')} </Text>
              </View>
            </View>
            {
              (text && text !== '') ?
                <View style={styles.viewContainParse}>
                 <ParsedText
                      style={styles.text}
                      parse={[
                        { type: 'url', style: styles.url, onPress: this.handleUrlPress },
                        { type: 'email', style: styles.email, onPress: this.handleEmailPress },
                        {
                          pattern: /\[(@[^:]+):([^\]]+)\]/i,
                          style: styles.username,
                          onPress: this.handleNamePress,
                          renderText: this.renderText
                        },
                        { pattern: /#(\w+)/, style: styles.hashTag }
                      ]}
                    >
                    {text}
                  </ParsedText>
                </View> : null
            }
            {
              ( (comment.data|| {} ).images && (comment.data|| {} ).images.length > 0 ) &&
              <TouchableOpacity 
                onPress={() => this._onPressImage((comment.data || {}).images[0])}
                style={[styles.touchImageComment]}>
                <FastImage
                  style={{
                    width: SCREEN.width - SIZE_IMAGE - 15*3,
                    height:180
                  }}
                  source={ UtiImage.getUrlImageStream( (comment.data|| {} ).images[0])}
                />
              </TouchableOpacity>
            }
          </TouchableOpacity>

          <View style={styles.viewContain}>
            <View style={styles.viewBottom}>
              <Text style={styles.commentTime}>{UtilDate.humanizeTimestamp(comment.created_at)}</Text>
              <ReactionLabelLikeChild {...comment} userIdCurrent={this.props.userIdCurrent} props={props} />
              <ReactionLabelCommentChild {...comment} onPressActivity={this._onPressChildComment} />
              <ReactionLabelLikeChild onShowModallize ={(comment) => onShowModallize(comment)} {...comment} isShowIcon={true} userIdCurrent={this.props.userIdCurrent} props={props} />
            </View>

            {!this.state.visibleCommentChild && children_counts > 0 && (
              <TouchableOpacity onPress={this._LoadCommentChild} style={styles.touchLabelChildren}>
                <Text style={styles.labelChildren}>
                  {label_children}
                  <Text style={styles.labelChildrenSecond}> {localization.t('comment_was_reply')}</Text>
                </Text>
                <Text style={styles.labelChildrenCount}>
                  {children_counts} {localization.t('comment_response')}
                </Text>
              </TouchableOpacity>
            )}
            {this.state.visibleCommentChild && (
              <View style={styles.viewChildren}>
                <Collapsible collapsed={!this.state.visibleCommentChild}>
                  {(this.state.dataCommentChild || []).map((item, index) => {
                    return (
                      <CommentItemChild
                        key={index}
                        userIdCurrent={userIdCurrent}
                        commentParent={comment}
                        onPressReplyChild={this._onPressChildParentComment}
                        comment={item}
                        index={index}
                        onShowModalCommentChild = {this._onShowModalCommentChild}
                      />
                    );
                  })}
                </Collapsible>
              </View>
            )}
          </View>
          {/* <View  style={{flexDirection:'row'}}>
                     <ReactionToggleLikeChild  {...comment} props={props} />
                     <ReactionToggleHeartChild { ...comment} props = {props} />
                     <ReactionCommentChild {...comment} onPressActivity={this._onPressChildComment} />
            </View> */}
        </View>
        <Modal
          onBackdropPress={() => this.setState({ visibleModal: false })}
          isVisible={this.state.visibleModal}
          onSwipeComplete={() => this.setState({ visibleModal: false })}
          style={styles.bottomModal}
        >
          <ModalContent
            isComment={true}
            isCommentChild={this.state.isCommentChild}
            comment={comment}
            commentChild={this.state.commentChild}
            commentParent={this.state.commentParent}
            onPressEdit={this._onPressEditComment}
            onPressEditCommentChild={this._onPressEditCommentChild}
            activity={this.state.activity}
            userId={this.state.userId}
            activityId={this.state.activityId}
            token={this.state.token}
            doReactionDeleteRequest={this._doReactionDeleteRequest}
            doReactionChildDeleteRequest={this._doReactionChildDeleteRequest}
            closeModal={this._closeModal}
          />
        </Modal>

        {/* View Image comment */}
        <ModalImageComment
                comment={comment}
                userId={this.props.userIdCurrent}
                isModalVisible={this.state.isModalVisible}
                urlViewImage={this.state.urlViewImage}
                closeModal={this._closeModal}
                props={props}
        />
      </View>
    );
  }
}

**Comment by jamesawer3** [comment]
@ThanhNghia944 Thank you so much

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  Please check it again for me thank you

**Comment by jamesawer3** [comment]
@ThanhNghia944  Can you update the code with main import methods and the way you export the comment custom component please. And what is that .get method you have used in the code???

**Comment by ThanhNghia944** [comment]
hi @jamesawer3  full code import for you 
import React, { PureComponent } from 'react';
import { View, Linking, TouchableOpacity, StyleSheet, Text } from 'react-native';
import UtilDate from '../../../utils/UtilDate';
import FastImage from 'react-native-fast-image';
import * as _ from 'lodash';
import UtiImage from '../../../utils/UtiImage';
import { SCREEN } from '../../../utils/UtilDeviceInfo';
import ParsedText from 'react-native-parsed-text';
import { ReactionToggleLikeChild } from './ReactionToggleLikeChild';
import { ReactionCommentChild } from './ReactionCommentChild';
import Collapsible from 'react-native-collapsible';
import CommentItemChild from './CommentItemChild';
import localization from '../../../localization';
import { ReactionLabelLikeChild } from './ReactionLabelLikeChild';
import { ReactionLabelCommentChild } from './ReactionLabelCommentChild';
import ModalContent from './ModalContent';
import Modal from 'react-native-modal';
import AppConfig from '../../../AppConfig';
import ModalImageComment from './Modal/ModalImageComment';
import Modalize from 'react-native-modalize';
import ModalContentToggle from '../component/Modal/ModalContentToggle'

 .get  from CommentList throught props

**Comment by jaapbakker88** [comment]
@ThanhNghia944 can you be a little bit more clear in sharing your code I'm going to need more than: 
```
this.setState({
dataCommentChild: ( (comment.latest_children || {}).comment || [] )
});
```
Please share your components code because from just this setState I can't guess what might be going wrong. Please also use backticks so I can actually read the code.

**Comment by ThanhNghia944** [comment]
Hi @jaapbakker88  
After I set withOwnChildren: true, an error occurred (before withOwnChildren: false, it ran ok)
this.setState({
dataCommentChild: ( (comment.latest_children || {}).comment || [] )
});

with 
+ dataCommentChild is the child comment array of a comment
+ comment from props comment parent
My idea is that I will get a child comment list from a parent comment and show it

<CommentItemChild
                        key={index}
                        userIdCurrent={userIdCurrent}
                        commentParent={comment}
                        onPressReplyChild={this._onPressChildParentComment}
                        comment={item}
                        index={index}
                        onShowModalCommentChild = {this._onShowModalCommentChild}
 />
and i will get list comment child from comment

{(this.state.dataCommentChild || []).map((item, index) => {
                    return (
                      <CommentItemChild
                        key={index}
                        userIdCurrent={userIdCurrent}
                        commentParent={comment}
                        onPressReplyChild={this._onPressChildParentComment}
                        comment={item}
                        index={index}
                        onShowModalCommentChild = {this._onShowModalCommentChild}
                      />
                    );
                  })}

(before withOwnChildren: false it ran ok after withOwnChildren true 
When I comment the child after I refresh it it is duplicated twice
<img width="381" alt="Screen Shot 2019-09-16 at 4 06 10 PM" src="https://user-images.githubusercontent.com/53257922/64945943-fdbc0900-d89b-11e9-9c74-0b0ccdbcb9c2.png">

**Comment by ThanhNghia944** [comment]
Ex: 
{
   "children_counts": {
      "comment": 1
   },
   "parent": "",
   "created_at": "2019-09-16T09:08:50.123045Z",
   "data": {
      "text": "Test comment"
   },
   "activity_id": "06288ac0-d859-11e9-8080-800177efb3c3",
   "user": {
      "created_at": "2019-08-23T09:24:40.784085Z",
      "updated_at": "2019-09-06T07:53:41.065635Z",
      "id": "5d0a08049df8340011e0a289",
      "data": {
         "lastName": "Nguyen Thanh",
         "gender": "male",
         "coverImage": "https://i0.wp.com/photos.smugmug.com/Portfolio/Full/i-mwrhZK2/0/ea7f1268/X2/GothamCity-X2.jpg?resize=1280%2C743&ssl=1",
         "name": "Nghia  Nguyen Thanh",
         "nickname": "NghiaNguyen",
         "firstName": "Nghia ",
         "birthday": "2019-08-31T13:37:02.795Z"
      }
   },
   "user_id": "5d0a08049df8340011e0a289",
   "kind": "comment",
   "updated_at": "2019-09-16T09:08:50.123045Z",
   "latest_children": {
      "comment": [
         {
            "children_counts": {},
            "parent": "ba25cd03-c211-4804-9ab7-26a947cc67f6",
            "created_at": "2019-09-16T09:09:03.340225Z",
            "data": {
               "text": "Test comment child"
            },
            "activity_id": "06288ac0-d859-11e9-8080-800177efb3c3",
            "user": {
               "created_at": "2019-08-23T09:24:40.784085Z",
               "updated_at": "2019-09-06T07:53:41.065635Z",
               "id": "5d0a08049df8340011e0a289",
               "data": {
                  "lastName": "Nguyen Thanh",
                  "gender": "male",
                  "coverImage": "https://i0.wp.com/photos.smugmug.com/Portfolio/Full/i-mwrhZK2/0/ea7f1268/X2/GothamCity-X2.jpg?resize=1280%2C743&ssl=1",
                  "name": "Nghia  Nguyen Thanh",
                  "nickname": "NghiaNguyen",
                  "phone": "03387666221",
                  "profileImage": "http://media.ilotusland.vn/uploads/profile/17-4-test-rig-featured-1920x915_1567258647878.jpg",
                  "firstName": "Nghia ",
                  "email": "nghia.nguyen@vietan-software.com",
                  "birthday": "2019-08-31T13:37:02.795Z"
               }
            },
            "user_id": "5d0a08049df8340011e0a289",
            "kind": "comment",
            "updated_at": "2019-09-16T09:09:03.340225Z",
            "latest_children": {},
            "id": "dc8e6ace-96b2-4977-968a-38c63114a518"
         },
         {
            "children_counts": {},
            "parent": "ba25cd03-c211-4804-9ab7-26a947cc67f6",
            "created_at": "2019-09-16T09:09:03.340225Z",
            "data": {
               "text": "Test comment child"
            },
            "activity_id": "06288ac0-d859-11e9-8080-800177efb3c3",
            "user": {
               "created_at": "2019-08-23T09:24:40.784085Z",
               "updated_at": "2019-09-06T07:53:41.065635Z",
               "id": "5d0a08049df8340011e0a289",
               "data": {
                  "lastName": "Nguyen Thanh",
                  "gender": "male",
                  "coverImage": "https://i0.wp.com/photos.smugmug.com/Portfolio/Full/i-mwrhZK2/0/ea7f1268/X2/GothamCity-X2.jpg?resize=1280%2C743&ssl=1",
                  "name": "Nghia  Nguyen Thanh",
                  "nickname": "NghiaNguyen",
                  "phone": "03387666221",
                  "profileImage": "http://media.ilotusland.vn/uploads/profile/17-4-test-rig-featured-1920x915_1567258647878.jpg",
                  "firstName": "Nghia ",
                  "email": "nghia.nguyen@vietan-software.com",
                  "birthday": "2019-08-31T13:37:02.795Z"
               }
            },
            "user_id": "5d0a08049df8340011e0a289",
            "kind": "comment",
            "updated_at": "2019-09-16T09:09:03.340225Z",
            "latest_children": {},
            "id": "dc8e6ace-96b2-4977-968a-38c63114a518"
         }
      ]
   },
   "own_children": {
      "comment": [
         {
            "children_counts": {},
            "parent": "ba25cd03-c211-4804-9ab7-26a947cc67f6",
            "created_at": "2019-09-16T09:09:03.340225Z",
            "data": {
               "text": "Test comment child"
            },
            "activity_id": "06288ac0-d859-11e9-8080-800177efb3c3",
            "user": {
               "created_at": "2019-08-23T09:24:40.784085Z",
               "updated_at": "2019-09-06T07:53:41.065635Z",
               "id": "5d0a08049df8340011e0a289",
               "data": {
                  "lastName": "Nguyen Thanh",
                  "gender": "male",
                  "coverImage": "https://i0.wp.com/photos.smugmug.com/Portfolio/Full/i-mwrhZK2/0/ea7f1268/X2/GothamCity-X2.jpg?resize=1280%2C743&ssl=1",
                  "name": "Nghia  Nguyen Thanh",
                  "nickname": "NghiaNguyen",
                  "phone": "03387666221",
                  "profileImage": "http://media.ilotusland.vn/uploads/profile/17-4-test-rig-featured-1920x915_1567258647878.jpg",
                  "firstName": "Nghia ",
                  "email": "nghia.nguyen@vietan-software.com",
                  "birthday": "2019-08-31T13:37:02.795Z"
               }
            },
            "user_id": "5d0a08049df8340011e0a289",
            "kind": "comment",
            "updated_at": "2019-09-16T09:09:03.340225Z",
            "latest_children": {},
            "id": "dc8e6ace-96b2-4977-968a-38c63114a518"
         }
      ]
   },
   "id": "ba25cd03-c211-4804-9ab7-26a947cc67f6"
}

**Comment by jaapbakker88** [comment]
@ThanhNghia944 yes i see something is wrong, but I can't say what's going wrong if you're not sharing all the code. Right now I'm just guessing. I tested in my own test app and childReactions are working fine, so i'm guessing something is wrong in your setup. But as long as I don't see what you're doing I can't say for sure.

**Comment by ThanhNghia944** [comment]
@jaapbakker88  full code 
from SinglePostScreen
https://pastebin.com/WFkACq6e
i get detail activity,and comment ,comment child
--- CommentItemCustom ( comment Parent ) 
https://pastebin.com/LcrDxmWX
i get list dataCommentChild and show CommentItemChild
https://pastebin.com/b4rfMRks
if i set withOwnChildren: false, it ran ok but error with like comment and withOwnChildren: true, comment like ok but error comment child

**Comment by jaapbakker88** [comment]
I'm not really sure what's going on in all your code. You wrote a lot of custom components that are impossible for me to debug without knowing what exactly you're doing. All I can say now I that the ChildReactions are working perfectly fine for me using our own CommentList. A couple of suggestions 
- try to use our components as we do a lot of complicated state management,
- Or start by taking a good look at our state management. 
- Start logging at different places where we request the feed. Do we actually return multiple ChildReactions? Then have a look at where they are added, maybe you're adding them twice?

There's many options why this might go wrong but for now with me being unable to run your code it's impossible for me to pinpoint what it might be.

**Comment by ThanhNghia944** [comment]
Why when I set withOwnChildren: false to run correctly, did you try to do the same as I did, both add comments and like

**Comment by ThanhNghia944** [comment]
Can you show me your example

**Comment by ThanhNghia944** [comment]
I noticed that when I took another account to comment, after the refresh it was not duplicated 
<img width="407" alt="Screen Shot 2019-09-16 at 4 59 59 PM" src="https://user-images.githubusercontent.com/53257922/64949507-8e4a1780-d8a3-11e9-904b-a50931f76c3e.png">

**Comment by ThanhNghia944** [comment]
i find a solution to solve this problem 
by remove half of the duplicate child comments
<img width="425" alt="Screen Shot 2019-09-16 at 5 25 06 PM" src="https://user-images.githubusercontent.com/53257922/64950998-fe0dd180-d8a6-11e9-8f39-d2d7b430e68b.png">
thank you for sp ^^

**Comment by jamesawer3** [comment]
@ThanhNghia944 Have you forked the code and customizing it according to your wish???

**Comment by ThanhNghia944** [comment]
@jamesawer3  sr I custom many things so I don't know how to help you

**Comment by jaapbakker88** [comment]
I'm seeing the issue now on my end as well. Please keep your solution for now while I work on a solution on my end.

**Comment by ThanhNghia944** [comment]
I just checked the like comment and found that the latest_children in the comment was also duplicated when viewing the list of people who liked it, you can try again by
Create a comment, like that comment, then unlike, then refresh, like that comment again -> then see the list of people who like it will be duplicated
then login another account -> see the list of people who like it, only 1
You can check it out

**Comment by ThanhNghia944** [comment]
<img width="409" alt="Screen Shot 2019-09-16 at 5 53 03 PM" src="https://user-images.githubusercontent.com/53257922/64952555-dc164e00-d8aa-11e9-8732-ca8adc8f114c.png">

**Comment by jamesawer3** [comment]
@ThanhNghia944 Thank you waiting for your code...

**Comment by ThanhNghia944** [comment]
Hi @jaapbakker88 
I wrote a bug example component from your lib example, you can check it out
--When first like -> It's right and shows my name
<img width="359" alt="Screen Shot 2019-09-16 at 11 23 55 PM" src="https://user-images.githubusercontent.com/53257922/64975394-14348580-d8d9-11e9-826e-480961c2fcc8.png">
after i unlike -> The likes count is correct but the latest_children still has my name in it ( { } )
this is a bug
<img width="337" alt="Screen Shot 2019-09-16 at 11 26 18 PM" src="https://user-images.githubusercontent.com/53257922/64975518-6675a680-d8d9-11e9-9e59-7d16299c3509.png">
when like again -> when I liked it again the list was repeated
<img width="354" alt="Screen Shot 2019-09-16 at 11 27 19 PM" src="https://user-images.githubusercontent.com/53257922/64975578-8d33dd00-d8d9-11e9-92ae-53e07af99ca8.png">
after i refresh and unlike again ->  list was repeated 
<img width="361" alt="Screen Shot 2019-09-16 at 11 28 19 PM" src="https://user-images.githubusercontent.com/53257922/64975633-afc5f600-d8d9-11e9-9cd4-781bc83b0658.png">

here mycode  same from your lib
SinglePostScreen 
https://pastebin.com/fyaChaKD

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88 Have you checked again?

**Comment by jaapbakker88** [comment]
I have as I said above, it's a bug on the backend. We're working on it. Please keep your solution filtering duplicates until we deploy a fix for this issue.

**Comment by ThanhNghia944** [comment]
hi @
jaapbakker88 thank you very much ^^

Vào Th 3, 17 thg 9, 2019 vào lúc 14:56 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by jamesawer3** [comment]
@ThanhNghia944 Waiting for your code... Can you please post it so that I can refer your code???

**Comment by ThanhNghia944** [comment]
hi @jamesawer3  full code for you https://pastebin.com/fyaChaKD

**Comment by jamesawer3** [comment]
@ThanhNghia944 I asked your whole getstream which you have fully redesigned. Can you please post it??? I want it for reference learning many things from your code!!! All the screens and design you posted were looking good

**Comment by jamesawer3** [comment]
@ThanhNghia944 @jaapbakker88 I have a doubt how to get the user's who have liked the child comment. Actually I get a user list but its showing parent like list and child comment like list. Can you guys help me???

**Comment by jaapbakker88** [comment]
@jamesawer3 you just loop over the comments or likes or whatever reactions and check if there's duplicates. Then you keep one. There's even a lodash function for this. https://lodash.com/docs#uniq

**Comment by jaapbakker88** [comment]
@ThanhNghia944 @jamesawer3 this issue should be fixed on the backend. Could you try and see if this issue is resolved for you?

**Comment by ThanhNghia944** [comment]
hi @jaapbakker88  It works fine for the comments but the only minor bug is list like 
(  options={{ withOwnChildren: true}} ) 
when first like  -> correct
<img width="350" alt="Screen Shot 2019-09-18 at 11 12 47 PM" src="https://user-images.githubusercontent.com/53257922/65165884-d9ae2280-da69-11e9-84dc-f921375d9773.png">
after unlike but Likes list is wrong 
<img width="374" alt="Screen Shot 2019-09-18 at 11 13 39 PM" src="https://user-images.githubusercontent.com/53257922/65165946-f77b8780-da69-11e9-8f29-8aaeede3abea.png">
like again -> it is looped
<img width="377" alt="Screen Shot 2019-09-18 at 11 14 05 PM" src="https://user-images.githubusercontent.com/53257922/65166007-11b56580-da6a-11e9-99d4-83ccb9265018.png">
Everything is correct after I refreshed 
<img width="361" alt="Screen Shot 2019-09-18 at 11 15 28 PM" src="https://user-images.githubusercontent.com/53257922/65166090-390c3280-da6a-11e9-974a-f6675498289b.png">
Only that bug remains, comments and likes remain stable

**Comment by jamesawer3** [comment]
Hi @ThanhNghia944 Can you send me you custom comment box code???

@jaapbakker88 @ThanhNghia944 How to reverse the order of flat feed

**Comment by ThanhNghia944** [comment]
@jamesawer3  full code for you https://pastebin.com/AhWXUA7q

**Comment by jaapbakker88** [comment]
@ThanhNghia944 is this a like on the comment or on the post?

**Comment by ThanhNghia944** [comment]
hi @ThanhNghia944  like on the comment

**Comment by jaapbakker88** [comment]
@ThanhNghia944 this is indeed a bug that became visible after the fix we did on the backend. I'll push a fix today.

**Comment by ThanhNghia944** [comment]
thank you @jaapbakker88  pls help me sp refresh after update I am about to reach the deadline with customers,pls pls

**Comment by jaapbakker88** [comment]
@ThanhNghia944 i just updated the library to version `0.8.17` which should contains a fix for this bug. Please let me know if this resolves this issue.

**Comment by ThanhNghia944** [comment]
Thank you it works very well

**Comment by jamesawer3** [comment]
hi @ThanhNghia944 @jaapbakker88 How to refresh the flatfeed automatically???

**Comment by fawwaz** [comment]
> I'm not really sure what's going on in all your code. You wrote a lot of custom components that are impossible for me to debug without knowing what exactly you're doing. All I can say now I that the ChildReactions are working perfectly fine for me using our own CommentList. A couple of suggestions
> 
> * try to use our components as we do a lot of complicated state management,
> * Or start by taking a good look at our state management.
> * Start logging at different places where we request the feed. Do we actually return multiple ChildReactions? Then have a look at where they are added, maybe you're adding them twice?
> 
> There's many options why this might go wrong but for now with me being unable to run your code it's impossible for me to pinpoint what it might be.

It might be a little bit of topic but I tried to use plain `<CommentList />` but it seems that it doesn't render child reaction. Do you know how to display child reaction properly ?

**Comment by nishiloxit** [comment]
Hi @fawwaz did you manage to resolve this issue? I am unable to render child reactions properly. So my 2nd level of comment cannot be properly liked. I notice it has something to do with own_children and latest_children.

**Comment by fawwaz** [comment]
Not yet @nishiloxit

**Comment by nishiloxit** [comment]
@fawwaz any workarounds you are using? I am using this in a production ready app and I am stuck at this.
