### ISSUE TITLE
How to refresh flat feed in background programmatically ?

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#83]
Hi @jaapbakker88,
 We just need to refresh the flatfeed content without reloading the screen and there should not be any loader displayed to the user.

**Comment by jaapbakker88** [comment]
What do you exactly need? If you pass `notify={true}` realtime get's enabled. This will show 'you have X new activities' if there's new activities.

**Comment by jamesawer3** [comment]
Nope I no need to show that instead of that i have to update it automatically

**Comment by jaapbakker88** [comment]
We don't currently support doing this. We looked at other companies that implemented feeds and there's usually no updating automatically. This has a reason, if you update automatically the feed is going to jump every time a new activity gets added. That's usually very bad UX. I'm sorry but we can't help you with this right now.

**Comment by jamesawer3** [comment]
Without jumping can't we update the feed???

**Comment by jaapbakker88** [comment]
That seems like a different issue from updating automatically. I'm still not sure what you mean, maybe you can use the following in your flatListProps: https://facebook.github.io/react-native/docs/flatlist.html#listheadercomponent

**Comment by ThanhNghia944** [comment]
i can help you in NewActivitiesNotification you can use props
 //refesh 
   this.setState({isRefesh:true} , () => { this.props.onPress();})
NewActivitiesNotification in   FlatFeed
 Notifier={element => {
          return <NewActivitiesNotification {...element} userId={this.state.userId} />;
  }}

**Comment by jamesawer3** [comment]
@jaapbakker88 How to call a method which returns the header inside the flatlistprops of [flatfeed](https://getstream.github.io/react-native-activity-feed/#flatfeed)

**Comment by jamesawer3** [comment]
@ThanhNghia944 What will do will it automatically refresh???

**Comment by ThanhNghia944** [comment]
@jamesawer3  yes ^^

**Comment by jamesawer3** [comment]
@ThanhNghia944 I think this will refresh only in owner feed, I want to automatically update it to other users too. For example if we send a message in whats app its refreshing in other user end like that this is just for example

**Comment by jamesawer3** [comment]
@jaapbakker88 waiting for your reply tried like you said

**Comment by jaapbakker88** [comment]
@ThanhNghia944 I'm really not sure what you want. We don't support the automatically updating. Because we think it's bad UX to implement it like that. Twitter, Facebook don't do this either. The other issue(which is a different issue i'm guessing?): I haven't tried it myself but guess it should work, Im not sure how to solve this issue for you but this does not seem related to our library.

**Comment by jamesawer3** [comment]
@jaapbakker88 are you telling me???

**Comment by ThanhNghia944** [comment]
hi jaapbakker88 You can try by adding more than 12 comments, and click
loadmore to see the problem, the list you return

Vào Th 4, 25 thg 9, 2019 vào lúc 14:36 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by jaapbakker88** [comment]
@jamesawer3 yes, that was meant for you.

**Comment by jamesawer3** [comment]
@jaapbakker88 you said to use [ListHeaderComponent](https://facebook.github.io/react-native/docs/flatlist.html#listheadercomponent) in flatlistprops right I tried that but I couldn't render it!!! Can you please provide me a example???

**Comment by jamesawer3** [comment]
> @jaapbakker88 How to call a method which returns the header inside the flatlistprops of [flatfeed](https://getstream.github.io/react-native-activity-feed/#flatfeed)
> 
> Tried like this,
> 
> ```
>          flatListProps={
>             ListHeaderComponent = () => { <View style={{ height: 100, backgroundColor: 'red' }} /> },
>             ListHeaderComponentStyle = { height: 100 }
>           }
> ```
> 
> But Header was not displaying

Check this!!!

**Comment by ThanhNghia944** [comment]
hi @jamesawer3  pls   ListHeaderComponent = () => { return <View style={{ height: 100, backgroundColor: 'red' }} /> },
            ListHeaderComponentStyle = { height: 100 }
^^ you don't return

**Comment by jaapbakker88** [comment]
@jamesawer3 please understand that I am looking at this, but this is not the only thing I'm working on. You seem very frustrated, but please keep in mind that everybody is doing their best.

**Comment by jaapbakker88** [comment]
@jamesawer3 also check @ThanhNghia944 answer

**Comment by jamesawer3** [comment]
If I set height for header even the feeds are displaying inside the view

![image](https://user-images.githubusercontent.com/43437378/65581515-3b561b80-df99-11e9-8a7e-99b4d78f90db.png)

**Comment by jaapbakker88** [comment]
For me this is working perfectly. Please share your code if you want me to look at it because I can't debug from an image. 

```
<FlatFeed Activity={renderActivity} notify flatListProps={{
        ListHeaderComponent: () =>  (<View style={{ height: 100, backgroundColor: 'red' }} />),
        ListHeaderComponentStyle: { height: 100 },
      }} />
```

![image](https://user-images.githubusercontent.com/1172870/65585054-1dc98780-df82-11e9-92a1-e807c5afe534.png)

**Comment by jamesawer3** [comment]
Got it @jaapbakker88 it's working fine

**Comment by jamesawer3** [comment]
If you can give some idea for auto load post it would be helpful for example like whatsApp

**Comment by jaapbakker88** [comment]
@jamesawer3 Yeah, as i've said multiple times, we don't support that you can try @ThanhNghia944's solution but I'm not sure if that will work. May I ask why you would want this at all as it's really bad UX?

**Comment by jamesawer3** [comment]
Sorry!!! for asking it again and again we did a UI like that, we got suggestions for displaying it automatically or is there a way to redesign the notification UI

**Comment by jaapbakker88** [comment]
I really don't know what I can do for you. We don't support this. And I don't know why you would want it. Also if you're asking questions please be clear about your questions because every time you leave me guessing what the issue is about. I don't know your project and what you're trying to do so I can't help you at all.

**Comment by jamesawer3** [comment]
Okay, thank you for your patience and thanks for replying one of my issue is solved but the actual reason of opening issue didnt solve incase if you are planning to refresh the feed automatically please do ping me.

**Comment by ThanhNghia944** [comment]
Why do you use my code i think it run exactly

Vào Th 4, 25 thg 9, 2019 lúc 18:28 jamesawer3 <notifications@github.com> đã
viết:

**Comment by jamesawer3** [comment]
@ThanhNghia944 will it refresh for others users also if a new post comes???

**Comment by ThanhNghia944** [comment]
Yes ^^

Vào Th 4, 25 thg 9, 2019 lúc 18:47 jamesawer3 <notifications@github.com> đã
viết:

**Comment by jamesawer3** [comment]
> i can help you in NewActivitiesNotification you can use props
> //refesh
> this.setState({isRefesh:true} , () => { this.props.onPress();})
> NewActivitiesNotification in FlatFeed
> Notifier={element => {
> return <NewActivitiesNotification {...element} userId={this.state.userId} />;
> }}

when this onpress method will be called

**Comment by ThanhNghia944** [comment]
when this onpress method will be called  -> you can subscribe notify in component did mount ^^

**Comment by jamesawer3** [comment]
@ThanhNghia944 @jaapbakker88 How to refresh the feed programmatically?

**Comment by akhilrichard** [comment]
@jamesawer3 
please try this,
Notifier={element => {
                if(this.state.isRefresh){
                  element.onPress();
                  this.setState({isRefresh:false})
                }
                return <NewActivitiesNotification  {...element} userId="Richy" />;
                }} />

**Comment by dubitoergo** [comment]
I'm also looking for some form of flat feed that updates automatically. @jaapbakker88 Why the emphasis on this idea being bad practice from a UI/UX perspective. A notification feed which updates by 'animating in' new activites from the top seems practical (and desirable) for a number of situations. Consider a component functioning as 'history'. If you'd like to update this feed in real-time as a user browses, real-time UI updates would be great. No? Thoughts? What am I missing about react-activity-feed? How would this best be implemented if not that way?
