### ISSUE TITLE
Bug comment when refresh page

### ISSUE THREAD

**Issue by ThanhNghia944** [GetStream/react-native-activity-feed#84]
Hi @jaapbakker88  
1.  First I click on the detail activity screen and click on loadmore, everything is ok 
<img width="397" alt="Screen Shot 2019-09-25 at 9 14 49 AM" src="https://user-images.githubusercontent.com/53257922/65563816-12bc2a80-df75-11e9-9df9-410ae512bba3.png">
<img width="418" alt="Screen Shot 2019-09-25 at 9 16 42 AM" src="https://user-images.githubusercontent.com/53257922/65563902-53b43f00-df75-11e9-9860-750d72cd1f58.png">

After that, I refreshed the page and click loadmore again 
This time there is a gap  
<img width="391" alt="Screen Shot 2019-09-25 at 9 19 07 AM" src="https://user-images.githubusercontent.com/53257922/65563996-a988e700-df75-11e9-84f4-bbcf2c3ece1f.png">

2. When the comment list is above 12, if I click loadmore, it will appear for the first time
<img width="394" alt="Screen Shot 2019-09-25 at 9 22 07 AM" src="https://user-images.githubusercontent.com/53257922/65564076-f8368100-df75-11e9-9036-103f6297449b.png">
<img width="406" alt="Screen Shot 2019-09-25 at 9 22 28 AM" src="https://user-images.githubusercontent.com/53257922/65564090-07b5ca00-df76-11e9-87f6-21a350b1a515.png">
But after that, I clicked to load the next, not showing the next comment list
<img width="381" alt="Screen Shot 2019-09-25 at 9 23 33 AM" src="https://user-images.githubusercontent.com/53257922/65564149-359b0e80-df76-11e9-813d-e1600aef04a9.png">
When I scroll, it displays 
<img width="400" alt="Screen Shot 2019-09-25 at 9 24 09 AM" src="https://user-images.githubusercontent.com/53257922/65564221-69763400-df76-11e9-9832-8b7a89efabc7.png">

**Comment by jaapbakker88** [comment]
Can you please leave out the screenshot and explain in detail. I'm not really sure what's happening. Also please fill in the issue template.

**Comment by jaapbakker88** [comment]
@ThanhNghia944 yes I've tried with many comments and I'm not seeing your issue. What are the exact steps?

**Comment by ThanhNghia944** [comment]
@jaapbakker88
The error occurred when I used the LoadMoreButton props do you use it?

LoadMoreButton={(props) => <LoadMoreButton {...props} onPress={props.onPress
}/>}

Vào Th 4, 25 thg 9, 2019 vào lúc 14:41 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by jaapbakker88** [comment]
@ThanhNghia944 can you also please provide the commentlist and it's props so I can see what you're doing there.

**Comment by ThanhNghia944** [comment]
Hi
jaapbakker88
this is my commentList
https://pastebin.com/vGGaiNmi
with  LoadMoreButton={(props) => <LoadMoreButton {...props} onPress={props.
onPress}/>}
and component LoadMoreButton
https://pastebin.com/ZGZ5yxX8

Vào Th 4, 25 thg 9, 2019 vào lúc 14:55 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by ThanhNghia944** [comment]
Have you tried checking, I think you'll get the same error as me when using
the LoadMoreButton props ^^

Vào Th 4, 25 thg 9, 2019 vào lúc 15:00 Nguyễn Tinikun <
nguyenthanhnghia944@gmail.com> đã viết:

**Comment by jaapbakker88** [comment]
Yeah I'm trying that, but not seeing the error. Also that CommentList is your component, but where are you rendering it and what props are you passing. This is mine: 
```
<CommentList
     // oldestToNewest={true}
     CommentItem={({ comment }) => (
        <React.Fragment>
            <CommentItem
                 comment={comment}
                 Footer={<LikeButton reaction={comment} {...props} />}
              />
         </React.Fragment>
      )}
      LoadMoreButton={(props) => (
         <TouchableOpacity onPress={props.onPress}><Text>test</Text> . 
         </TouchableOpacity>
      )}
    activityId={props.activity.id}
    reactions={props.activity.latest_reactions} 
/>
```

**Comment by ThanhNghia944** [comment]
Hi
sorry i forgot to tell you, if you set reverseOrder it will be as faulty as
me

Vào Th 4, 25 thg 9, 2019 vào lúc 15:43 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by ThanhNghia944** [comment]
<CommentList
                    {...props}
                    flatListProps={{
                       style: {
                       }, 
                       ItemSeparatorComponent: this._renderSeparator,
                    }}
                    activityId={(props.activity || {}).id}
                    reactions={(props.activity || {}).latest_reactions} 
                    reverseOrder
                    noPagination={false}
                    oldestToNewest ={false}
                    infiniteScroll={false} //false: show ButtonLoadmore
                    LoadMoreButton={(props) => <LoadMoreButton {...props} onPress={props.onPress}/>}
         you can check ! thank you very much ^^

**Comment by jaapbakker88** [comment]
@ThanhNghia944 even with reverseOrder this is working fine for me. 

```
<CommentList
                  reverseOrder
                  CommentItem={({ comment }) => (
                    <React.Fragment>
                      <CommentItem
                        comment={comment}
                        Footer={<LikeButton reaction={comment} {...props} />}
                      />
                    </React.Fragment>
                  )}
                  LoadMoreButton={(props) => <TouchableOpacity onPress={props.onPress}><Text>test</Text></TouchableOpacity>}
                  activityId={props.activity.id}
                  reactions={props.activity.latest_reactions} />
```

**Comment by ThanhNghia944** [comment]
ok I'll check and respond to you
thank you very much ^^

Vào Th 4, 25 thg 9, 2019 vào lúc 18:47 jaapbakker88 <
notifications@github.com> đã viết:

**Comment by jamesawer3** [comment]
@ThanhNghia944 https://github.com/GetStream/react-native-activity-feed/issues/83#issuecomment-534986670

**Comment by ThanhNghia944** [comment]
Hi jamesawer3 I'm sick today so I haven't checked, I'm in the hospital,
I'll answer you as soon as possible

Vào Th 5, 26 thg 9, 2019 vào lúc 14:16 jamesawer3 <
notifications@github.com> đã viết:

**Comment by jamesawer3** [comment]
Okay carry on take care take rest

**Comment by jamesawer3** [comment]
@jaapbakker88 Have a doubt, When posting a feed I'm modifying the data 

```
         modifyActivityData={(data) => {
                return { ...data, to: [`user:${currentUser._id}`] }
         }
```

When I'm posting I kept break point at data and checked, created date is coming as 16/09/2019 and time is 2:30PM but my actual time is 30.09.2019 and my time is 8 PM. Now my doubt is do I have to send created at date in param's ???

**Comment by ThanhNghia944** [comment]
Hi @jaapbakker88 
Sorry my bad, thank you very much ^^

**Comment by jaapbakker88** [comment]
Cool, going to close this issue now as all things seem to be resolved.

**Comment by jamesawer3** [comment]
> @jaapbakker88 Have a doubt, When posting a feed I'm modifying the data
> 
> ```
>          modifyActivityData={(data) => {
>                 return { ...data, to: [`user:${currentUser._id}`] }
>          }
> ```
> 
> When I'm posting I kept break point at data and checked, created date is coming as 16/09/2019 and time is 2:30PM but my actual time is 30.09.2019 and my time is 8 PM. Now my doubt is do I have to send created at date in param's ???

@jaapbakker88 Any update on this???
