### ISSUE TITLE
How to handle images posted in feed

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#85]
Hi @jaapbakker88,
When I post an image in feed its getting stretched and I can't view the full image. How to handle the images posted in feed? I want to see the full image

@ThanhNghia944 Do you have any idea?

![IMG_0170](https://user-images.githubusercontent.com/43437378/66988331-fcbb0900-f0df-11e9-8d48-a39a7dde49ca.jpg)

**Comment by jaapbakker88** [comment]
@jamesawer3 are you using our Activity component or your own custom component. Please be clear when you submit issues, I can't guess from just a screenshot and one line of text what might be going on.

**Comment by jamesawer3** [comment]
Nope I'm using your component only

**Comment by ThanhNghia944** [comment]
Hi @jamesawer3  Sorry but I uploaded the image from my server ^^

**Comment by jamesawer3** [comment]
How to change URLPreview default image???

**Comment by jamesawer3** [comment]
@ThanhNghia944 Do you have idea about how to handle statusupdateform image and submit button

**Comment by ThanhNghia944** [comment]
Hi @jamesawer3  because i upload image my server So I will upload the image first to get the link and then when I click submit I will update it to the database

**Comment by jamesawer3** [comment]
I'm asking about the styles @ThanhNghia944

**Comment by ThanhNghia944** [comment]
Hi  @jamesawer3  style for image , i use FastImage to view image
<img width="354" alt="Screen Shot 2019-10-23 at 1 30 06 PM" src="https://user-images.githubusercontent.com/53257922/67364185-405aba80-f599-11e9-908a-8287b7779452.png">
<img width="363" alt="Screen Shot 2019-10-23 at 1 29 31 PM" src="https://user-images.githubusercontent.com/53257922/67364195-4486d800-f599-11e9-88b3-f2723380a1ce.png">

**Comment by jamesawer3** [comment]
Ohh okay I'm using statusupdateform for updating status i have issue with UI in android

**Comment by jamesawer3** [comment]
@ThanhNghia944 How you are handling submit button for posting? How you are sending message, image to StreamApp

**Comment by ThanhNghia944** [comment]
Ohh okay I'm using statusupdateform for updating status i have issue with UI in android

 you can you 
import { KeyboardAccessoryView } from 'react-native-keyboard-accessory';

 <KeyboardAccessoryView
          inSafeAreaView={false}
          alwaysVisible={true}
          hideBorder={true}
          androidAdjustResize={true} // FIX AUTO ADJUST ANDROID
          avoidKeyboard={true} //FIX AVOID VIEW IOS
        >

**Comment by jamesawer3** [comment]
> @ThanhNghia944 How you are handling submit button for posting? How you are sending message, image to StreamApp

How you are send the data to StreamApp?

**Comment by ThanhNghia944** [comment]
you can use api 
router.post('/timeline/post', checkTokenLogin , async (req, res) => {
  try {
    let timeline = await create(req.body);
    resSuccess(res, {data: timeline})
  }
  catch(err) {
    resError(res, err.message)
  }
})

const configs = _.get( (user || {} ).organization,'timeline.configs',{});
        let client = connectStream(configs.key,configs.secret,configs.appId);
await client.feed( form.feedGroup + '',form.user_id + '' ).addActivity(activity);

**Comment by jamesawer3** [comment]
Okay thanks let me try, how you are posting images???

**Comment by ThanhNghia944** [comment]
hi i post my server ^^ i use https://github.com/joltup/rn-fetch-blob

**Comment by jamesawer3** [comment]
Okay, Thank you!!!

**Comment by jamesawer3** [comment]
This is my code
```
onSubmitPressed: ({ auth, description }) => () => {
      var client = stream.connect(getStreamConfig().apiKey, auth.user.getStreamUserToken, getStreamConfig().appId);
      var user1 = client.feed('user', auth.user._id);
      var activity = { 'actor': user1, 'verb': 'post', 'object': description };
      user1.addActivity(activity);
    }
```

I'm getting this error when trying to post
```
Unhandled JS Exception: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'StreamClient'
    |     property 'currentUser' -> object with constructor 'StreamUser'
    --- property 'client' closes the circle
```

**Comment by jamesawer3** [comment]
@jaapbakker88 Can you please help me to post a message in timeline feed???

**Comment by jamesawer3** [comment]
@ThanhNghia944 can I get some contact info for contacting you personally??? I have few doubts in  your code

**Comment by jamesawer3** [comment]
@ThanhNghia944 

> Hi @jamesawer3 style for image , i use FastImage to view image
> <img alt="Screen Shot 2019-10-23 at 1 30 06 PM" width="354" src="https://user-images.githubusercontent.com/53257922/67364185-405aba80-f599-11e9-908a-8287b7779452.png">
> <img alt="Screen Shot 2019-10-23 at 1 29 31 PM" width="363" src="https://user-images.githubusercontent.com/53257922/67364195-4486d800-f599-11e9-88b3-f2723380a1ce.png">

Can I get this full code???

**Comment by ThanhNghia944** [comment]
Hi @jamesawer3  ^^
because I have customized many library components so when I send you, maybe you will not understand, what do you want me to help you with?

**Comment by jamesawer3** [comment]
how you are aligning that images

**Comment by jamesawer3** [comment]
@ThanhNghia944 How you are showing the image after uploading to activity

**Comment by ThanhNghia944** [comment]
Hi @jamesawer3  you can show ^^ 
<img width="424" alt="Screen Shot 2019-11-05 at 8 51 38 AM" src="https://user-images.githubusercontent.com/53257922/68172287-8c4e2c00-ffa9-11e9-97e5-7f6feedb46d9.png">

**Comment by jamesawer3** [comment]
You are not rendering images according to its height like fb???

**Comment by ThanhNghia944** [comment]
hi i do like facebook ^^

**Comment by jamesawer3** [comment]
> Hi @jamesawer3 you can show ^^
> <img alt="Screen Shot 2019-11-05 at 8 51 38 AM" width="424" src="https://user-images.githubusercontent.com/53257922/68172287-8c4e2c00-ffa9-11e9-97e5-7f6feedb46d9.png">

In this only one image is posted???
