### ISSUE TITLE
How to post a custom url in feed

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#86]
Hi @jaapbakker88 ,

How to post a custom url in feed and how to handle onPress???

**Comment by jaapbakker88** [comment]
Hello @jamesawer3, i'm not sure what you mean. 

Posting a url should make it a URL and makes it clickable.

**Comment by jamesawer3** [comment]
If i post www.facebook.com its not taking as URL

**Comment by ThanhNghia944** [comment]
Hi @jamesawer3  you can use lib react-native-parser-text to custom content

**Comment by jamesawer3** [comment]
For that i have to write my custom component right???

**Comment by jamesawer3** [comment]
Okay will check it. Any how thank you and are you fine now you said you were in hospital???

**Comment by ThanhNghia944** [comment]
I'm fine and have been discharged from the hospital, thank you very much ^^

**Comment by jamesawer3** [comment]
How to change URLPreview default image in react-native-activity-feed component???

**Comment by ThanhNghia944** [comment]
hi you can use
 <TouchableOpacity style={[styles.avatarContainer,styleTouch]} 
            onPress={ this.handlePressImage}>
                { !this.state.isImgLoaded &&
                <Image
                      style={[styles.avatar,styleImage, {position:'absolute'}]} 
                      source={ defaultImage}
                      resizeMode={resizeMode}/>  
                }
                <FastImage
                  style={[styles.avatar,styleImage]} 
                  source={UtiImage.getLink(urlImage)}
                  onLoadStart={this.handleImgLoadStart}
                  onLoadEnd={this.handleImgLoaded}
                  onError= {this.handleImgError}
                  resizeMode={resizeMode}
                />
        </TouchableOpacity>



handleImgError(){
  this.setState({isImgLoadError: true,isImgLoaded: false})
}
handleImgLoaded(){
  if( !this.state.isImgLoadError){
    this.setState({isImgLoaded: true,isImgLoadError:false})
  }
}
handleImgLoadStart(){
  this.setState({isImgLoaded: false,isImgLoadError:false})
}
handlePressImage(){
    const { open} = this.props;
    if( open){
        open();
    }
}
