### ISSUE TITLE
FlatFeed with userId in parent component state

### ISSUE THREAD

**Issue by matheusmatos** [GetStream/react-native-activity-feed#89]
### **Setup:**
- **iOS or Android?** iOS
- **Expo or regular React Native?** Expo
- **React Native Version:** expo-sdk-35.0.0 (based in RN 0.59)
- **expo-activity-feed version:** 0.8.17
- **getstream version:** 4.3.0

### **Description of the bug**
I'm not sure if it's a bug or a desired behaviour. When I try to set the FlatFeed `userId` prop on my component state, the FlatFeed doesn't update when I update my state. Let me show with some code for best understanding:

```typescript
import React from 'react';
import { Text, View, SafeAreaView } from 'react-native';
import { StreamApp, FlatFeed } from 'expo-activity-feed';


export interface LocationProps { userId: string }
export interface LocationState { userId: string, updated: boolean }

class LocationFeed extends React.Component<LocationProps, LocationState> {
  constructor(props) {
    super(props)
    this.state = {
      userId: props.userId,
      updated: false
    }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        userId: "worldland",
        updated: true
      })
    }, 2000)
  }

  render () {
    console.log("I'M RENDERING NOW", "=>", "updated: " + this.state.updated)
    return (
      <View>
        <Text>Showing location = {this.state.userId}, updated: {this.state.updated ? "true" : "false"}</Text>
        <FlatFeed
          feedGroup="location"
          userId={this.state.userId}
        />
      </View>
    )
  }
}

export default function App() {
  return (
    <SafeAreaView>
      <StreamApp
        apiKey="<your_api_key>"
        appId="<your_app_id>"
        userId="<your_user_id>"
        defaultUserData={{ name: "Your default name" }}
        token="<your_user_token>"
        analyticsToken="<your_analytics_token>"
      >
        <LocationFeed userId="earth" />
      </StreamApp>
    </SafeAreaView>
  );
}
```

That's what I see on console:
```
Running application on iPhone 11 Pro Max.
I'M RENDERING NOW => updated: false
now listening to changes in realtime for location:earth
I'M RENDERING NOW => updated: true
```

I was expecting one more line with `now ... in realtime for location:worldland`. Also, the activities don't update and the GetStream API is not called again for the new userId.

### **To Reproduce**

1. Create a new project with `expo init` and choose the blank typescript template;
2. Install `expo-activity-feed` using yarn;
3. Replace the content of `App.tsx` with the code above;
4. Replace the getstream credentials with yours;
5. At this point, you will see that.

### **Additional context**
In my real context, the feed group name is "location" too and I asked GetStream support to change the security rules while the development. I don't know if it changes something.

Can anyone help me?

*P.S.: I would like to say thanks for all the hard-working on this library!*

**Comment by jaapbakker88** [comment]
@matheusmatos as I'm understanding you want to replace the feed with the other user's feed as soon as you change the userId.

To achieve this you probably want to replace the whole FlatFeed once the userId updates. We do some checks to avoid unnecessary rerenders and this changing the userId like this is not supported right now.

**Comment by gchazot** [comment]
@matheusmatos I've noticed this behaviour and found a work-around  that seems to work fine for me. By passing a `key` prop to a component you can suggest to react to re-render it.

```JSX
return (
    <StreamApp userId={userId}>
        <FlatFeed
            feedGroup={targetGroup}
            userId={targetId}
            notify={true}
            Activity={ActivityComponent}
        />
    </StreamApp>
);
```
This was my initial code, it would not update when changing `userId` `targetGroup` or `targetId` props.

I updated it like this:
```JSX
const key = `${userId} ${targetGroup} ${targetId}`;  // Just hashing the variables

return (
    <StreamApp userId={userId} key={key}>
        <FlatFeed
            feedGroup={targetGroup}
            userId={targetId}
            notify={true}
            Activity={ActivityComponent}
        />
    </StreamApp>
);
```

It also works with the `key` prop on `<FlatFeed>`  when `userId` is a constant
