### ISSUE TITLE
Refresh FlatFeed when new comments are added 

### ISSUE THREAD

**Issue by asvine-p** [GetStream/react-native-activity-feed#91]
**Setup (always fill this in):**

- iOS or Android? 
=> Both

- Expo or regular React Native?
=> Regular React Native

- React Native Version:
=> 0.61.4

- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
=> react-native-activity-feed@0.8.17 / react-native-activity-feed-core@0.8.17

- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`
=> getstream@4.3.0

**Describe the bug**

Hello. When I add comments in a post, the flat-feed doesn't show any notification and does not refresh automatically. I am using the FlatFeed on a screen, and a ReactionList in another one. When user clicks on comment to a post, it will bring him to a new screen with a singlePost on top, and the reaction list below it. Here is the code of the commentListScreen:

```js
const onAddComment = (activityProps, commentText) => {
    const { onAddReaction } = activityProps;

    onAddReaction('comment', activity, {
      text: commentText,
    });
  };

return 
 <ScreenContainer>
      <TopBar title={t('team.tab.feed.comments')} withBack />
      <Container behavior={isAndroid ? 'height' : 'padding'} enabled>
        <HeroesStreamApp>
          <SinglePost
            activity={activity}
            feedGroup={feedGroup}
            userId={groupId}
            options={{ withOwnChildren: true }}
            Activity={props => {
              return (
                <ListContainer>
                  <TeamActivity
                    key={props.activity.id}
                    userId={groupId}
                    withFooter={false}
                    activityProps={props}
                    feedGroup={feedGroup}
                  />
                  <ReactionList
                    flatListProps={{
                      ref: commentListRef,
                    }}
                    activityId={props.activity.id}
                    reactionKind={'comment'}
                    reverseOrder
                    Reaction={({ reaction }) => {
                      return <TeamCommentItem comment={reaction} />;
                    }}
                  />
                </ListContainer>
              )
            }}
            Footer={props => (
              <CommentInputContainer>
                <CommentInput
                  userName={userName}
                  picture={profilePic}
                  onPublishComment={comment => onAddComment(props, comment)}
                />
              </CommentInputContainer>
            )}
          />
        </HeroesStreamApp>
      </Container>
    </ScreenContainer>
```

The comment list is updated automatically. But when I go back to the FlatFeedScreen, I need to pull to refresh to see the comments number being updated.

Is there any way do display a notification or to refresh the feed programatically ?

**To Reproduce**

1. Click on a Activity
2. Came to a CommentList
3. Add NewComment to the current activity.
4. Go back to FeedScreen. 
5. The feed was not updated.

**Expected behavior**
When arriving in feedScreen, update programmatically the feed or display a NewActivitiesNotification
to notify the user to update the list

Thanks for you help.

**Screenshots**

**Additional context**
The code of the feed screen

```js
const Feed = ({ groupId, feedGroup, navigation, groupMeta, user, t }: FeedProps) => {
  const userId = `group_${groupId}`;
  const [selectedActivity, selectActivity] = useState(null);
  const theme = useTheme();
  useOnScreenFocused(() => {}, navigation);

  const deleteActivity = async streamAppProps => {
    try {
      const { activity } = selectedActivity;
      await streamAppProps.client.feed(feedGroup, user._id).removeActivity(activity.id);
      selectActivity(null);
    } catch (e) {}
  };

  return (
    <FeedContainer>
      <HeroesStreamApp>
        <StreamApp.Consumer>
          {streamAppProps => {
            return (
              <FlatFeed
                notify
                withOwnReaction
                doReactionAddRequest={reaction => console.log('_____ADD_REACTION', reaction)}
                Notifier={props => (
                  <NewActivitiesNotification
                    styles={{ backgroundColor: theme.color.primary }}
                    {...props}
                  />
                )}
                userId={userId}
                feedGroup={feedGroup}
                Activity={props => (
                  <TeamActivity
                    key={props.activity.id}
                    groupId={userId}
                    userId={user._id}
                    onEditActivity={() => selectActivity(props)}
                    withFooter={true}
                    activityProps={props}
                    feedGroup={feedGroup}
                  />
                )}
              >
                <>
                  <FeedHeader groupMeta={groupMeta} />
                  <FeedTitle>{t('team.tab.feed.news')}</FeedTitle>
                  <SendMessageButton feedGroup={feedGroup} groupId={groupId} />
                  <EditActivityModal
                    onDeletePressed={() => deleteActivity(streamAppProps)}
                    isVisible={selectedActivity !== null}
                    activity={selectedActivity}
                    onCloseModal={() => selectActivity(null)}
                  />
                </>
              </FlatFeed>
            );
          }}
        </StreamApp.Consumer>
      </HeroesStreamApp>
    </FeedContainer>
  );
};
```

**Comment by asvine-p** [comment]
Is there anyone here ?

**Comment by jaapbakker88** [comment]
Hey @asvine-p I looked into this and can confirm the flatfeed is not updated automatically, I will look into updating this to make sure it works. Keep an eye on this issue.

**Comment by asvine-p** [comment]
Waiting for your reply ! Thanks

**Comment by Antoine-C** [comment]
@jaapbakker88 Can confirm this is still an issue, any ETA on this behavior ? 
Thank's

**Comment by jaapbakker88** [comment]
@Antoine-C @asvine-p recently we've added the `setListRef` prop to FlatFeed and NotificationFeed. This allows you to create your own reference to the FlatList underneath which will allow you to do anything to the FlatList. For instance refresh it. It works like this.
`setListRef={(ref) => this.refToList = ref}`

You should be able to refresh it that way. Let me know if this helps?

**Comment by Antoine-C** [comment]
@jaapbakker88 Thank's for this props, everything works like a charm with this !

**Comment by asvine-p** [comment]
Hi @jaapbakker88. It seems to work. 
Thanks for posting a fix. It seems to work by using 
```feedRef.props.onRefresh(true)```
Not sure it's the best way to do it, but it does the job.

Thanks !

**Comment by mayuri-pansuriya** [comment]
> Hi @jaapbakker88. It seems to work.
> Thanks for posting a fix. It seems to work by using
> `feedRef.props.onRefresh(true)`
> Not sure it's the best way to do it, but it does the job.
> 
> Thanks !

@jaapbakker88 Can you tell me how we can call this function?
