### ISSUE TITLE
Issue importing react-native-activity-feed

### ISSUE THREAD

**Issue by JJZolper** [GetStream/react-native-activity-feed#95]
I've been following:

https://www.npmjs.com/package/expo-activity-feed

I do not use Expo, but native code. I'm getting a bundling error:

error: bundling failed: Error: Unable to resolve module `react-native-activity-feed`

when I do:

import { StreamApp } from 'react-native-activity-feed';

It is definitely in my node modules. Obviously, I'm trying to get this imported not with expo-activity-feed but react-native-activity-feed.

I'm wondering though if it's on the npm install as I get:

% npm i react-native-activity-feed --save
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN notsup Unsupported engine for getstream@4.3.0: wanted: {"node":">=4.8 <=12"} (current: {"node":"13.5.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: getstream@4.3.0
npm WARN react-native-activity-feed-core@0.8.17 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-activity-feed-core@0.8.17 requires a peer of react-native@~0.55.2 but none is installed. You must install peer dependencies yourself.

As you can see I'm running node 13.5.0, it appears that is not supported with getstream@4.3.0. Is this something that can be put on the readme and tracked? Also, has anyone else had the issue where it's not installing dependencies? Maybe I have an issue with my package manager npm vs yarn. I've been confused with what to use because I see both used a lot.

**Comment by JJZolper** [comment]
I believe I was able to get around the problems by force linking an older version of node, be it 12.14.0. Then also using yarn 1.13.0, installing that with npm. I believe now I have react-native-activity-feed
 included as a pod and in the code itself. Would be advisable to button this up still though in terms of the node dependency. I believe I'm just ignoring the peer dependencies for react and react-native as I have newer versions.

**Comment by jaapbakker88** [comment]
@JJZolper I'll check into the node versions. Is this issue resolved otherwise? Regarding using npm or yarn, I always use yarn to install packages as it's much faster.

**Comment by JJZolper** [comment]
@jaapbakker88 Thank you! I believe for now it is because I don't think it is complaining about using the code from that package. My VSCode acts a little funny though. I know getting code always updated to the latest is a full job but if possible it wouldn't be bad because then I don't have to specify versions of Yarn or Node in order to install. I'm new to Yarn and React Native still so some of this could be user error. Fine to close this if you'd like unless you want to report back. I'm in the process of trying to use this great example: https://github.com/GetStream/react-native-example now. The example like I said is great the issue I have though is adapting in the user token in the real world is proving challenging for me. I won't drag on here but I may post an issue there. Struggling with my existing classes and adopting the feed app.
